export const LEVELS = ['A2', 'B1', 'B2', 'C1'];

const rows = [
['A2','Sounds good.','That works for me.','Звучит хорошо.',['Dinner at seven? Sounds good.','We can meet outside the station. Sounds good.']],
['A2','No worries.','It is not a problem.','Без проблем.',['No worries, I can wait.','No worries — it happens.']],
['A2','I don’t mind.','I am okay with either option.','Я не против.',['Tea or coffee? I don’t mind.','I don’t mind waiting a few minutes.']],
['A2','It’s up to you.','You can decide.','Решать тебе.',['We can stay in or go out — it’s up to you.','Pick any restaurant. It’s up to you.']],
['A2','I have no idea.','I really do not know.','Понятия не имею.',['Where did he go? I have no idea.','I have no idea how this works.']],
['A2','That’s fine.','That is acceptable.','Всё нормально.',['Ten minutes later? That’s fine.','If you need to cancel, that’s fine.']],
['A2','I’m not sure.','I do not know or I am uncertain.','Я не уверен.',['I’m not sure what time it starts.','I’m not sure that’s a good idea.']],
['A2','Of course.','Certainly; yes.','Конечно.',['Can you help me? Of course.','Of course I remember.']],
['A2','Not really.','Not very much or not exactly.','Не особо.',['Do you like horror films? Not really.','Are you tired? Not really.']],
['A2','Why not?','I am open to the idea.','Почему бы и нет?',['Want to grab coffee? Why not?','We could walk there. Why not?']],
['A2','Take your time.','There is no need to hurry.','Не торопись.',['Take your time — I’m not in a rush.','Take your time with the form.']],
['A2','Here you go.','Said when giving something to someone.','Вот, держи.',['Here you go — your coffee.','You needed the key? Here you go.']],
['A2','I’m on my way.','I have left and I am coming now.','Я уже в пути.',['I’m on my way. I’ll be there in ten minutes.','Don’t worry, I’m on my way.']],
['A2','Give me a minute.','Wait for a short time.','Дай мне минуту.',['Give me a minute — I’m almost done.','Can you give me a minute?']],
['A2','I’m good.','I am fine, or I do not need anything.','Всё нормально / мне не надо.',['More coffee? I’m good, thanks.','How are you? I’m good.']],
['A2','That’s enough.','No more is needed.','Этого достаточно.',['That’s enough sugar, thanks.','Okay, that’s enough for today.']],
['A2','It doesn’t matter.','It is not important.','Это неважно.',['Which seat? It doesn’t matter.','It doesn’t matter what we order.']],
['A2','I’m ready.','I can start now.','Я готов.',['Are you ready to go? I’m ready.','I’m ready when you are.']],
['A2','See you later.','Goodbye for now.','Увидимся позже.',['I’m heading out. See you later.','See you later at home.']],
['A2','Let me check.','I will verify it.','Дай я проверю.',['What time is the flight? Let me check.','Let me check my calendar.']],
['A2','I think so.','I believe the answer is yes.','Думаю, да.',['Is she coming? I think so.','Will it fit? I think so.']],
['A2','I don’t think so.','I believe the answer is no.','Думаю, нет.',['Is this the right street? I don’t think so.','Will he agree? I don’t think so.']],
['A2','What do you mean?','Ask someone to explain.','Что ты имеешь в виду?',['What do you mean by “later”?','What do you mean? I thought it was cancelled.']],
['A2','That’s right.','That is correct.','Верно.',['So we meet at eight? That’s right.','That’s right — exactly.']],
['A2','I’ll be right back.','I will return very soon.','Я сейчас вернусь.',['I’ll be right back — I forgot my phone.','Wait here. I’ll be right back.']],

['B1','It depends.','The answer changes with the situation.','Зависит от обстоятельств.',['Is it expensive? It depends where you buy it.','Are you coming tonight? It depends.']],
['B1','That makes sense.','I understand the logic.','В этом есть смысл.',['That makes sense. Let’s do it that way.','Now that you explain it, that makes sense.']],
['B1','Fair enough.','I accept your point or decision.','Ладно, справедливо.',['I’d rather stay home. Fair enough.','Fair enough — you warned me.']],
['B1','My bad.','It was my mistake.','Моя ошибка.',['My bad — I sent the wrong file.','I thought it was Tuesday. My bad.']],
['B1','I’m down.','I am interested and willing.','Я за.',['Pizza tonight? I’m down.','I’m down for a quick trip this weekend.']],
['B1','I mean...','Used to clarify, correct, or add detail.','В смысле / я имею в виду.',['I mean, we could leave earlier.','It was good — I mean, better than I expected.']],
['B1','Actually...','Used to correct or add surprising information.','Вообще-то / на самом деле.',['Actually, I’ve already seen that film.','I thought it was Friday, but actually it’s Thursday.']],
['B1','Apparently...','According to what I heard or learned.','Оказывается / по-видимому.',['Apparently, the meeting was moved.','He’s apparently leaving next month.']],
['B1','To be honest...','Used before giving an honest opinion.','Честно говоря.',['To be honest, I’m exhausted.','To be honest, I didn’t enjoy it.']],
['B1','At least...','Used to mention one positive or minimum point.','По крайней мере.',['At least we tried.','It’ll take at least an hour.']],
['B1','As far as I know...','Based on the information I have.','Насколько я знаю.',['As far as I know, she still works there.','As far as I know, there’s no deadline.']],
['B1','I’ll figure it out.','I will find a solution or understand it.','Я разберусь.',['Don’t worry — I’ll figure it out.','I’ll figure out how to connect it.']],
['B1','That’s the point.','That is the main idea or reason.','В этом и смысл.',['It’s difficult. That’s the point.','That’s the point — we need a simpler system.']],
['B1','I ended up...','The final result was unexpected or unplanned.','В итоге я...',['I ended up staying home.','We ended up taking a taxi.']],
['B1','It turns out...','The real result or truth was discovered later.','Оказалось, что...',['It turns out we were on the wrong train.','It turns out she already knew.']],
['B1','I’m used to it.','It feels normal because I have experience with it.','Я к этому привык.',['The traffic is bad, but I’m used to it.','I’m used to working late.']],
['B1','I’m not used to it.','It still feels unfamiliar.','Я к этому не привык.',['I’m not used to this heat.','I’m not used to speaking in public.']],
['B1','It’s not a big deal.','It is not very important or serious.','Ничего страшного.',['Don’t worry, it’s not a big deal.','We can fix it. It’s not a big deal.']],
['B1','I get it.','I understand.','Я понял.',['Okay, I get it now.','I get it — you need more time.']],
['B1','You never know.','Something unexpected may happen.','Никогда не знаешь.',['Take an umbrella — you never know.','Maybe they’ll call back. You never know.']],
['B1','It’s worth it.','The result justifies the time, money, or effort.','Оно того стоит.',['It’s expensive, but it’s worth it.','The hike is hard, but the view is worth it.']],
['B1','I’m just saying.','I am only expressing a point, not forcing it.','Я просто говорю.',['I’m just saying, we could leave earlier.','You don’t have to agree — I’m just saying.']],
['B1','That works for me.','I agree with that plan or time.','Меня устраивает.',['Six thirty? That works for me.','If you drive, that works for me.']],
['B1','I can’t make it.','I cannot attend or arrive.','Я не смогу прийти.',['Sorry, I can’t make it tonight.','I can’t make it to the meeting.']],
['B1','I’ll keep you posted.','I will update you when I know more.','Буду держать в курсе.',['I’ll keep you posted about the flight.','I don’t know yet, but I’ll keep you posted.']],
['B1','Let’s see how it goes.','We will try and judge by the result.','Посмотрим, как пойдёт.',['Let’s try it for a week and see how it goes.','I’m not sure yet. Let’s see how it goes.']],
['B1','I’m looking forward to it.','I am happy and excited about something future.','Я этого жду с нетерпением.',['The trip is next week — I’m looking forward to it.','I’m looking forward to seeing you.']],
['B1','That rings a bell.','It sounds familiar.','Что-то знакомое.',['That name rings a bell.','I don’t remember exactly, but it rings a bell.']],
['B1','I’ll get back to you.','I will reply later after checking.','Я вернусь к тебе с ответом.',['Let me check the numbers and I’ll get back to you.','I’ll get back to you this afternoon.']],
['B1','No rush.','There is no need to hurry.','Не спеши.',['Send it when you can — no rush.','No rush, I’ll be here.']],

['B2','I’m not entirely sure.','I have some doubt.','Я не до конца уверен.',['I’m not entirely sure that will work.','I’m not entirely sure what he meant.']],
['B2','I’m not so sure about that.','I disagree or have doubts about that idea.','Я бы не был так уверен.',['I’m not so sure about that — the data looks weak.','You think it’ll be easy? I’m not so sure about that.']],
['B2','That’s not necessarily true.','The statement may not always be correct.','Это не обязательно так.',['That’s not necessarily true in every case.','Higher price means better quality? That’s not necessarily true.']],
['B2','From my point of view...','Used to introduce your perspective.','С моей точки зрения.',['From my point of view, the simpler option is better.','From my point of view, we need more time.']],
['B2','The way I see it...','Used to explain your personal view.','Как я это вижу.',['The way I see it, we have two choices.','The way I see it, timing is the main issue.']],
['B2','I see where you’re coming from.','I understand the reasoning behind your opinion.','Я понимаю твою логику.',['I see where you’re coming from, but I still disagree.','I see where you’re coming from — it is a risk.']],
['B2','You’ve got a point.','Your argument is valid.','В этом ты прав.',['You’ve got a point. We should check first.','You’ve got a point about the cost.']],
['B2','That being said...','Used to add a contrasting point.','При этом / тем не менее.',['It’s expensive. That being said, the quality is excellent.','I disagree. That being said, I understand the concern.']],
['B2','For the most part...','Mostly, but not completely.','По большей части.',['For the most part, everything went smoothly.','The team agreed for the most part.']],
['B2','For what it’s worth...','Used before offering information or an opinion that may help.','Если это что-то значит.',['For what it’s worth, I think you handled it well.','For what it’s worth, I had the same problem.']],
['B2','As it turns out...','Used to introduce a discovered result.','Как оказалось.',['As it turns out, the issue was simple.','As it turns out, we had met before.']],
['B2','It slipped my mind.','I forgot it unintentionally.','Вылетело из головы.',['Sorry, it completely slipped my mind.','I meant to call you, but it slipped my mind.']],
['B2','I can’t help but...','I cannot stop myself from doing or feeling something.','Не могу не...',['I can’t help but laugh at that.','I can’t help but wonder what happened.']],
['B2','I might as well...','There is no strong reason not to do it.','Можно уж / пожалуй.',['I’m already here, so I might as well stay.','We might as well take a taxi.']],
['B2','I’d rather...','I prefer one option.','Я бы предпочёл.',['I’d rather wait until tomorrow.','I’d rather not talk about it now.']],
['B2','It’s about time.','Something should have happened earlier.','Давно пора.',['It’s about time we left.','It’s about time they fixed that road.']],
['B2','That’s easier said than done.','Something sounds simple but is difficult in practice.','Легче сказать, чем сделать.',['Just relax. — Easier said than done.','Saving money is easier said than done.']],
['B2','I wouldn’t go that far.','I think that statement is too strong.','Я бы не заходил так далеко.',['It was disappointing, but I wouldn’t go that far.','Terrible? I wouldn’t go that far.']],
['B2','It’s a long story.','The explanation is complicated or lengthy.','Долгая история.',['Why did you quit? It’s a long story.','How did you two meet? It’s a long story.']],
['B2','Long story short...','Used to give only the key result.','Короче говоря.',['Long story short, we missed the flight.','Long story short, they accepted the offer.']],
['B2','I’m on the fence.','I have not decided between two options.','Я пока не определился.',['I’m still on the fence about buying it.','I’m on the fence — both options are good.']],
['B2','I’m leaning towards...','I currently prefer one option slightly.','Я склоняюсь к...',['I’m leaning towards the second option.','I’m leaning towards staying another day.']],
['B2','Let’s not jump to conclusions.','We should not decide before we have enough facts.','Не будем делать поспешных выводов.',['Let’s not jump to conclusions until we check.','We only know one side, so let’s not jump to conclusions.']],
['B2','I’ll take your word for it.','I will believe what you say without checking.','Поверю тебе на слово.',['If you say it’s good, I’ll take your word for it.','I’ve never been there, so I’ll take your word for it.']],
['B2','It’s not the end of the world.','The problem is not as serious as it feels.','Это не конец света.',['We missed the train, but it’s not the end of the world.','One mistake is not the end of the world.']],

['C1','Be that as it may...','Used to accept a point before contrasting it.','Как бы то ни было.',['Be that as it may, we still need a decision today.','Be that as it may, the result is encouraging.']],
['C1','To put it another way...','Used to restate an idea more clearly.','Иными словами.',['To put it another way, we need fewer steps.','To put it another way, the plan is too expensive.']],
['C1','By and large...','Generally speaking.','В целом.',['By and large, the rollout went well.','People were, by and large, supportive.']],
['C1','All things considered...','After thinking about every important factor.','Учитывая всё.',['All things considered, I’d accept the offer.','All things considered, it was a good year.']],
['C1','To some extent...','Partly, but not completely.','В некоторой степени.',['I agree to some extent.','That explains the delay to some extent.']],
['C1','Up to a point...','True only within certain limits.','До определённой степени.',['I agree with you up to a point.','That works up to a point, but not at scale.']],
['C1','As far as that goes...','Regarding that particular point.','Что касается этого.',['As far as that goes, I have no objections.','As far as that goes, the numbers look fine.']],
['C1','That’s beside the point.','That information is not relevant to the main issue.','Это не относится к сути.',['Whether he meant it is beside the point.','That’s beside the point — we need to fix the process.']],
['C1','For all intents and purposes...','In practical terms, even if not technically exact.','Практически / по сути.',['For all intents and purposes, the project is finished.','The two versions are, for all intents and purposes, identical.']],
['C1','I’m inclined to think...','I tend to believe something, though not with full certainty.','Я склонен считать.',['I’m inclined to think the delay was avoidable.','I’m inclined to think we should wait.']],
['C1','I wouldn’t rule it out.','I think it remains possible.','Я бы не исключал.',['I wouldn’t rule out another attempt.','A delay is unlikely, but I wouldn’t rule it out.']],
['C1','There’s more to it than that.','The situation is more complex than it seems.','Всё сложнее.',['There’s more to it than that — cost is only one factor.','It looks simple, but there’s more to it than that.']],
['C1','That’s a fair assessment.','That is a reasonable evaluation.','Это справедливая оценка.',['That’s a fair assessment of the situation.','I think that’s a fair assessment.']],
['C1','I’m not convinced.','I do not find the argument persuasive.','Я не убеждён.',['I’m not convinced this solves the real problem.','The idea is interesting, but I’m not convinced.']],
['C1','It remains to be seen.','We do not yet know the final result.','Это ещё предстоит выяснить.',['Whether it works remains to be seen.','It remains to be seen how users will react.']],
['C1','That’s open to interpretation.','Different people may understand it differently.','Это можно трактовать по-разному.',['The ending is open to interpretation.','What he meant is open to interpretation.']],
['C1','I take your point.','I understand and acknowledge your argument.','Я понимаю твою мысль.',['I take your point, but I still prefer option B.','I take your point about timing.']],
['C1','I beg to differ.','A polite but firm way to disagree.','Позволю себе не согласиться.',['I beg to differ — the evidence suggests otherwise.','You think it was easy? I beg to differ.']],
['C1','That’s a bit of a stretch.','That claim seems exaggerated or hard to believe.','Это уже натяжка.',['Calling it a disaster is a bit of a stretch.','That explanation is a bit of a stretch.']],
['C1','It’s a matter of perspective.','The answer depends on how you look at it.','Это вопрос точки зрения.',['Is that a lot of money? It’s a matter of perspective.','Success is often a matter of perspective.']],
['C1','There’s no getting around it.','The fact or problem cannot be avoided.','От этого никуда не деться.',['There’s no getting around it: we need more time.','There’s no getting around the cost.']],
['C1','I’m under the impression that...','I currently believe something based on what I know.','У меня сложилось впечатление, что...',['I’m under the impression that the plan changed.','I was under the impression that you had agreed.']],
['C1','That doesn’t quite add up.','The facts do not seem consistent.','Что-то тут не сходится.',['His explanation doesn’t quite add up.','The numbers don’t quite add up.']],
['C1','Let’s leave it at that.','Let us stop discussing it here.','Давай на этом закончим.',['We clearly disagree, so let’s leave it at that.','I’ve said what I think. Let’s leave it at that.']],
['C1','I’ll give you that.','I admit that one part of your argument is correct.','Тут соглашусь.',['The design is better, I’ll give you that.','It was fast, I’ll give you that.']]
];

export const PHRASES = rows.slice(0, 100).map((r, i) => ({ id: `p${String(i+1).padStart(3,'0')}`, level:r[0], phrase:r[1], explanation:r[2], ru:r[3], examples:r[4] }));

export const VIDEOS = [
  { id:'v1', level:'B1', accent:'UK', topic:'Everyday phrases', title:'I use these phrases every day', channel:'English with Lucy', duration:'15 min', url:'https://www.youtube.com/watch?v=W6rtPM4jO3E', note:'Natural British phrases in context.' },
  { id:'v2', level:'B1', accent:'US', topic:'Daily conversation', title:'15 Daily English Phrases that you NEED to know', channel:'Speak English With Vanessa', duration:'Lesson', url:'https://www.youtube.com/watch?v=929f0gCkQL0', note:'Natural American English for daily use.' },
  { id:'v3', level:'B2', accent:'UK', topic:'Conversation markers', title:'Useful phrases for English conversation', channel:'BBC Learning English', duration:'Masterclass', url:'https://www.youtube.com/watch?v=HaJ01IG-50U', note:'Discourse markers such as “I mean” and “to tell you the truth”.' },
  { id:'v4', level:'B2', accent:'UK', topic:'Idioms & phrases', title:'30 common everyday phrases', channel:'English with Lucy', duration:'14 min', url:'https://www.youtube.com/watch?v=T4AZLYMiYMw', note:'Common British expressions and idioms.' }
];

export const COLLOCATIONS = [
  ['deal with an issue','handle a problem','разобраться с проблемой'],
  ['raise an issue','mention a problem for discussion','поднять вопрос'],
  ['make an effort','try hard','приложить усилия'],
  ['come to a decision','finally decide','прийти к решению'],
  ['take into account','consider something','принять во внимание'],
  ['keep in mind','remember and consider','иметь в виду'],
  ['run out of time','have no time left','не успевать / время закончилось'],
  ['work something out','find a solution','разобраться / решить'],
  ['bring something up','introduce a topic','поднять тему'],
  ['get back on track','return to the right direction','вернуться в нужное русло'],
  ['make a difference','have a meaningful effect','иметь значение'],
  ['take it for granted','fail to appreciate something because it seems guaranteed','принимать как должное']
].map((x,i)=>({id:`c${i+1}`, phrase:x[0], explanation:x[1], ru:x[2]}));

export const VERBS = [
  ['go','went','gone'],['see','saw','seen'],['take','took','taken'],['get','got','got/gotten'],['give','gave','given'],['know','knew','known'],['think','thought','thought'],['come','came','come'],['find','found','found'],['make','made','made'],['say','said','said'],['tell','told','told'],['leave','left','left'],['feel','felt','felt'],['bring','brought','brought']
].map((v,i)=>({id:`iv${i+1}`, base:v[0], past:v[1], participle:v[2]}));
