import assert from 'node:assert/strict';
import React from 'react';
import {create,act} from 'react-test-renderer';
import {createServer} from 'vite';
import {makeSession} from '../src/lesson-engine.js';
import {vocabularyTask} from '../src/vocabulary-tasks.js';
import {lexiconForLevel} from '../src/lexicon.js';
import {securedItem} from './learning-fixtures.mjs';
import {isSecured} from '../src/mastery.js';
const server=await createServer({define:{'import.meta.env.VITE_COUPLE_SYNC_URL':'""'},server:{middlewareMode:true},appType:'custom'});
globalThis.IS_REACT_ACT_ENVIRONMENT=true;
const now=Date.parse('2026-10-04T09:00:00Z'),oldNow=Date.now,oldFetch=globalThis.fetch;Date.now=()=>now;
let requests=0,root;globalThis.fetch=async()=>{requests++;throw Error('No production calls in UI tests');};
const disk=new Map();globalThis.localStorage={getItem:k=>disk.get(k)||null,setItem:(k,v)=>disk.set(k,v)};
const css=new Map(),viewportListeners=new Set();
globalThis.document={hidden:false,body:{style:{}},documentElement:{dataset:{},style:{setProperty:(k,v)=>css.set(k,v)}},addEventListener(){},removeEventListener(){},createElement:()=>({})};
globalThis.window={innerHeight:680,visualViewport:{height:680,addEventListener:(type,fn)=>viewportListeners.add(fn),removeEventListener:(type,fn)=>viewportListeners.delete(fn)},Telegram:{WebApp:{viewportStableHeight:680}},addEventListener(){},removeEventListener(){}};
globalThis.getComputedStyle=()=>({getPropertyValue:()=> '#fff9f2'});
const h=React.createElement,button=label=>root.root.findAllByType('button').find(n=>n.children.join('')===label);
try {
  const {default:App,Lesson,CheckScreen}=await server.ssrLoadModule('/src/AppV5.jsx');
  const item=lexiconForLevel('B1').find(i=>i.examples?.length&&i.exampleRu?.length),task=vocabularyTask(item,'write',[],0);
  assert.equal(task.type,'write');
  const session={...makeSession('B1'),task,step:3};let submitted=[];
  await act(async()=>{root=create(h(Lesson,{session,ascent:{steps:0,total:80,percent:0},onAnswer:v=>submitted.push(v)}));});
  const footer=root.root.findByType('footer'),form=root.root.findByType('form');
  assert.equal(button('Проверить').props.form,form.props.id);assert.equal(footer.findAllByType('button')[0],button('Проверить'));
  assert.equal(form.findAllByType('button').length,0);assert.equal(button('Проверить').props.disabled,true);
  await act(async()=>root.root.findByType('textarea').props.onChange({target:{value:'   '}}));assert.equal(button('Проверить').props.disabled,true);
  await act(async()=>root.root.findByType('textarea').props.onChange({target:{value:task.answer}}));assert.equal(button('Проверить').props.disabled,false);
  await act(async()=>form.props.onSubmit({preventDefault(){}}));assert.deepEqual(submitted,[task.answer]);
  await act(async()=>root.update(h(Lesson,{session:{...session,step:4},ascent:{steps:0,total:80,percent:0}})));
  assert.equal(button('Проверить').props.disabled,true);
  await act(async()=>root.unmount());
  console.log('✓ submit control belongs to the persistent footer, uses the matching form, rejects blanks and resets for a new card');

  disk.set('eft3:browser:settings',JSON.stringify({at:now,data:{level:'B1',profileName:'Artur',minutes:15,updatedAt:now}}));
  disk.set('eft3:browser:progress:B1',JSON.stringify({[item.id]:securedItem(now)}));
  disk.set('eft3:browser:wallet',JSON.stringify({earned:{old:{at:now-1000,amount:30}},spent:{},goals:{}}));
  disk.set('eft3:browser:activeLesson',JSON.stringify({at:now,data:session}));
  await act(async()=>{root=create(h(App));});
  assert.equal(css.get('--lesson-height'),'680px');window.visualViewport.height=350;
  await act(async()=>{for(const fn of viewportListeners)fn();});assert.equal(css.get('--lesson-height'),'350px');
  window.visualViewport.height=680;await act(async()=>{for(const fn of viewportListeners)fn();});
  await act(async()=>button('Продолжить урок →').props.onClick());
  await act(async()=>root.root.findByType(Lesson).props.onAnswer('An entirely different sentence.'));
  const stored=JSON.parse(disk.get('eft3:browser:progress:B1'))[item.id];
  assert.equal(isSecured(stored),true);assert.equal(stored.sentenceRecallPending,true);assert.equal(stored.w,0);
  assert.equal(Object.values(JSON.parse(disk.get('eft3:browser:wallet')).earned).reduce((sum,r)=>sum+r.amount,0),30);
  assert.match(JSON.stringify(root.toJSON()),/Закрепление слова не сброшено/);
  assert.equal(root.root.findAllByProps({className:'sentenceFeedback'}).length,1);
  assert.equal(root.root.findAllByProps({className:'compactYourAnswer sentenceAttempt'}).length,1);
  await act(async()=>root.root.findByType(Lesson).props.onBack());
  await act(async()=>root.unmount());
  assert.equal(viewportListeners.size,0);
  await act(async()=>{root=create(h(App));});
  await act(async()=>button('Продолжить урок →').props.onClick());
  assert.equal(root.root.findByType(Lesson).props.session.selected,'An entirely different sentence.');
  assert.equal(isSecured(JSON.parse(disk.get('eft3:browser:progress:B1'))[item.id]),true);
  await act(async()=>root.unmount());
  console.log('✓ actual app preserves mastery and $30 after a writing mismatch and exit/reload; feedback explains the separate recall');

  const check={id:'qa',level:'B1',quarter:1,tasks:[{type:'recall',prompt:'отправить',answer:'send',item}],index:0};
  await act(async()=>{root=create(h(CheckScreen,{value:check,onAnswer(){}}));});
  assert.equal(button('Проверить').props.form,root.root.findByType('form').props.id);
  assert.equal(root.root.findAllByType('details').length,0);
  await act(async()=>root.update(h(CheckScreen,{value:{...check,selected:'own answer'},onAnswer(){}})));
  assert.equal(button('Проверить'),undefined);assert.ok(button('Завершить контрольную'));
  assert.equal(root.root.findAllByType('details').length,0);assert.equal(requests,0);
  console.log('✓ checkpoint submit moves to the footer, keeps answers hidden and cannot submit a saved response again');
} finally {if(root)await act(async()=>root.unmount());Date.now=oldNow;globalThis.fetch=oldFetch;await server.close();}
