// Original examples. These are useful editorial selections, not a corpus frequency ranking.
export const B1_EXTRA = [
['I ran into someone.', 'I met someone unexpectedly.', 'Я случайно встретил кого-то.', 'I ran into my neighbour at the airport while we were both waiting for coffee.', 'We ran into an old colleague on our way to lunch and stopped for a quick chat.', 'If you run into Anna at work, could you ask her to call me?', 'People'],
['I came across something.', 'I found something without looking for it.', 'Я случайно наткнулся на что-то.', 'I came across a small café while I was looking for the bus stop.', 'We came across an old photo while we were packing for the move.', 'If you come across a cheaper flight, send me the link.', 'Everyday'],
['I’ve run out of time.', 'There is no time left to finish something.', 'У меня закончилось время.', 'I’ve run out of time, so I’ll send the rest of the report tomorrow.', 'We ran out of time before we could visit the museum.', 'I don’t want to run out of time at the airport; let’s leave early.', 'Work'],
['We’ve run out of milk.', 'We have used all the milk we had.', 'У нас закончилось молоко.', 'We’ve run out of milk. Could you pick some up on your way home?', 'I realised we had run out of milk after I made the coffee.', 'We keep running out of milk, so let’s buy a bigger bottle.', 'Home'],
['Can you give me a hand?', 'Ask someone to help with a task.', 'Можешь мне помочь?', 'Can you give me a hand? This suitcase is too heavy to lift on my own.', 'Could you give me a hand with dinner while I finish this call?', 'My colleague gave me a hand with the spreadsheet before the meeting.', 'People'],
['I’ll sort it out.', 'I will deal with the problem.', 'Я с этим разберусь.', 'I’ll sort it out. You shouldn’t have been charged twice for the same order.', 'We need to sort out the booking before Friday.', 'The landlord sorted out the broken shower the next morning.', 'Problems'],
['Let’s put it off.', 'Suggest doing something later instead.', 'Давай отложим это.', 'Let’s put it off until Saturday; neither of us has enough time tonight.', 'We put off buying a car until we knew our monthly costs.', 'I keep putting off that difficult phone call, but I need to make it today.', 'Plans'],
['Something came up.', 'An unexpected event changed my plans.', 'Возникли непредвиденные дела.', 'Something came up at work, and I won’t be able to leave at six.', 'We had planned to meet, but something came up and she had to cancel.', 'If anything comes up, call me before you make a decision.', 'Plans'],
['I’m running late.', 'I will arrive later than planned.', 'Я опаздываю.', 'I’m running late because the bus hasn’t arrived yet. Please start without me.', 'We were running late, so we skipped breakfast and bought food at the station.', 'Let me know if you’re running late and I’ll move the reservation.', 'Travel'],
['I got held up.', 'Something delayed me.', 'Меня задержали обстоятельства.', 'I got held up in traffic and missed the start of the film.', 'Sorry we’re late; we got held up at passport control.', 'If you get held up at work, I can pick up the shopping.', 'Travel'],
['I’ll catch up with you.', 'I will join you later or reach your position.', 'Я тебя догоню / присоединюсь позже.', 'I’ll catch up with you at the restaurant; I need to finish one email.', 'Go ahead and start walking. I’ll catch up with you in a minute.', 'We can catch up with the others after we leave our bags at the hotel.', 'Plans'],
['Let’s catch up.', 'Suggest talking about what has happened recently.', 'Давай пообщаемся и расскажем новости.', 'Let’s catch up over coffee this weekend. I haven’t heard about your new job.', 'We caught up after work and talked about our holiday plans.', 'It was lovely catching up with you after so long.', 'People'],
['I need to catch up on sleep.', 'I need more sleep after not sleeping enough.', 'Мне нужно отоспаться.', 'I need to catch up on sleep after working late three nights in a row.', 'We spent Sunday at home catching up on sleep after the trip.', 'I’ll join you tomorrow; tonight I need to catch up on sleep.', 'Home'],
['I’ll pick you up.', 'I will collect you, usually in a vehicle.', 'Я за тобой заеду.', 'I’ll pick you up outside the station so you don’t have to carry your bags far.', 'Can you pick me up after the appointment?', 'We picked them up from the airport and drove straight home.', 'Travel'],
['Can you drop me off?', 'Ask someone to leave you at a place on their journey.', 'Можешь меня высадить?', 'Can you drop me off near the supermarket? I’ll walk home from there.', 'She dropped us off outside the hotel before going to work.', 'You can drop me off here; the road ahead is closed.', 'Travel'],
['Let me know.', 'Tell me when you have information or a decision.', 'Дай мне знать.', 'Let me know when you’ve booked the tickets and I’ll arrange the taxi.', 'Could you let me know whether Friday works for you?', 'I’ll let you know as soon as the parcel arrives.', 'Plans'],
['I haven’t got round to it.', 'I have not found time to do it yet.', 'Я пока до этого не добрался.', 'I haven’t got round to it. The form is still sitting on my desk.', 'We haven’t got round to choosing a hotel yet.', 'I finally got round to calling the insurance company this morning.', 'Work'],
['I’m about to leave.', 'I am going to leave very soon.', 'Я вот-вот уйду.', 'I’m about to leave, so call me now if you need anything from the shop.', 'We were about to order when our friends arrived.', 'The meeting is about to start; let’s find a quiet room.', 'Plans'],
['I was wondering if...', 'Introduce a polite request or question.', 'Я хотел спросить, не...', 'I was wondering if we could move the meeting to Thursday.', 'I was wondering if you had a room with a sea view available.', 'I was wondering if you could explain this charge on my bill.', 'Requests'],
['Would you mind...?', 'Ask politely whether someone will do something.', 'Не мог бы ты...?', 'Would you mind closing the window? It’s difficult to hear the call.', 'Would you mind waiting here while I check your reservation?', 'Would you mind sending me the address again?', 'Requests'],
['Do you happen to know...?', 'Ask politely whether someone has some information.', 'Ты случайно не знаешь...?', 'Do you happen to know what time the last bus leaves?', 'Do you happen to know who is organising the meeting?', 'Do you happen to know a good place to eat nearby?', 'Requests'],
['Could you go over that again?', 'Ask someone to explain something one more time.', 'Можешь ещё раз это объяснить?', 'Could you go over that again? I didn’t understand the last step.', 'The accountant went over the figures again before we signed.', 'Can we go over the route before we leave the hotel?', 'Work'],
['What do you reckon?', 'Ask for an opinion; informal, especially British English.', 'Как думаешь?', 'What do you reckon? Should we book this hotel or keep looking?', 'I reckon we can finish the first part before lunch.', 'What do you reckon about leaving a day earlier?', 'Opinions'],
['That sounds like a plan.', 'Show agreement with a proposed plan.', 'Хороший план.', 'That sounds like a plan. I’ll book the table and you can invite the others.', 'We’ll take the early train and have breakfast there. That sounds like a plan.', 'A short walk followed by dinner? That sounds like a plan.', 'Plans'],
['I’d better get going.', 'I should leave now.', 'Мне пора идти.', 'I’d better get going if I want to catch the last bus.', 'It’s been lovely seeing you, but I’d better get going.', 'We’d better get going; the airport road gets busy after five.', 'People'],
['I’ll leave it with you.', 'I will let you handle or decide this.', 'Оставлю это на твоё усмотрение.', 'I’ll leave it with you. Choose whichever supplier can deliver by Friday.', 'Thanks for checking the booking; I’ll leave it with you.', 'I’ve explained what we need, so I’ll leave the details with you.', 'Work'],
['I didn’t mean to.', 'I did something unintentionally.', 'Я не хотел / не специально.', 'I didn’t mean to wake you. I thought you were still working.', 'I didn’t mean to sound rude; I was worried about the deadline.', 'She didn’t mean to miss the call. Her phone was on silent.', 'People'],
['I must have missed it.', 'I probably failed to notice something.', 'Видимо, я это пропустил.', 'I must have missed it. Could you forward the email again?', 'There was a sign at the entrance, but we must have missed it.', 'You mentioned the change yesterday? I must have missed that part.', 'Work'],
['I should have checked.', 'I regret not checking earlier.', 'Надо было проверить.', 'I should have checked the opening hours before driving all this way.', 'We should have checked the weather before leaving our coats at home.', 'I should have checked the total before sending the report.', 'Problems'],
['I can’t afford to...', 'I do not have enough money, time or room for the risk.', 'Я не могу себе позволить...', 'I can’t afford to buy a new laptop this month.', 'We can’t afford to miss the last connection.', 'I can’t afford to take another day off before the deadline.', 'Money'],
['I’m trying to cut down on...', 'I am trying to use or consume less of something.', 'Я стараюсь сократить...', 'I’m trying to cut down on coffee because I’m not sleeping well.', 'We’re trying to cut down on taxi journeys and walk more.', 'I’ve cut down on eating out so I can save for the trip.', 'Home'],
['I’m saving up for...', 'I am keeping money to buy or do something later.', 'Я коплю на...', 'I’m saving up for a holiday, so I’m bringing lunch from home.', 'We’re saving up for a new washing machine.', 'She saved up for six months before buying her first bike.', 'Money'],
['It’s on me.', 'I will pay for this.', 'Я угощаю.', 'It’s on me. You paid for dinner last time.', 'Let’s get a coffee before the train; it’s on me.', 'The taxi is on me because you helped me move all those boxes.', 'Money'],
['Shall we split the bill?', 'Suggest that everyone pays a share of the cost.', 'Разделим счёт?', 'Shall we split the bill, or would you rather pay for what you ordered?', 'We split the bill equally after dinner.', 'Let’s split the taxi fare since we’re going to the same place.', 'Money'],
['Could I get a refund?', 'Ask to have your money returned.', 'Можно вернуть деньги?', 'Could I get a refund? The headphones stopped working after two days.', 'We got a refund when the concert was cancelled.', 'You’ll need the receipt if you want to ask for a refund.', 'Shopping'],
['It doesn’t fit.', 'It is not the right size or shape.', 'Не подходит по размеру.', 'It doesn’t fit. Do you have the same jacket in a larger size?', 'The new table doesn’t fit through the kitchen door.', 'I tried the shoes on at home and realised they didn’t fit properly.', 'Shopping'],
['I’m just looking, thanks.', 'Politely say you do not need help in a shop yet.', 'Я пока просто смотрю, спасибо.', 'I’m just looking, thanks. I’ll ask if I need another size.', 'The assistant offered help, but I said I was just looking.', 'We’re just looking today; we want to compare a few models first.', 'Shopping'],
['Can I try it on?', 'Ask to put on clothing to check it.', 'Можно примерить?', 'Can I try it on? I’m not sure which size I need.', 'She tried the coat on over her jumper.', 'You should try the shoes on and walk around before buying them.', 'Shopping'],
['I’ve changed my mind.', 'I have made a different decision.', 'Я передумал.', 'I’ve changed my mind. I’d rather stay in and cook tonight.', 'We changed our minds about the hotel after reading the cancellation policy.', 'Let me know if you change your mind about coming with us.', 'Decisions'],
['I’ll think it over.', 'I will consider it carefully before deciding.', 'Я это обдумаю.', 'I’ll think it over and give you an answer tomorrow morning.', 'We need to think the offer over before signing anything.', 'Take the weekend to think it over; there’s no pressure to decide now.', 'Decisions'],
['I’m not in the mood.', 'I do not feel like doing that now.', 'Я не в настроении.', 'I’m not in the mood for a crowded restaurant after such a long day.', 'She wasn’t in the mood to discuss work during dinner.', 'If you’re not in the mood for a film, we can just talk.', 'People'],
['I could do with...', 'I would welcome or benefit from something.', 'Мне бы не помешало...', 'I could do with a short break before we start the next task.', 'After that long walk, we could do with something cold to drink.', 'The flat could do with a fresh coat of paint.', 'Home'],
['I feel like...', 'I want to do or have something.', 'Мне хочется...', 'I feel like going for a walk before dinner.', 'Do you feel like watching something funny tonight?', 'I didn’t feel like cooking, so I made a sandwich.', 'Home'],
['It’s been a while.', 'A long time has passed since something happened.', 'Давно не виделись / давно это было.', 'It’s been a while since we last had a proper conversation.', 'It’s been a while. How is the new job going?', 'We haven’t visited that beach in months; it’s been a while.', 'People'],
['We get on well.', 'We have a friendly relationship.', 'Мы хорошо ладим.', 'We get on well even though we have very different interests.', 'Do you get on well with your new manager?', 'I’ve always got on well with the neighbours upstairs.', 'People'],
['We have a lot in common.', 'We share many interests or experiences.', 'У нас много общего.', 'We have a lot in common, especially our taste in music.', 'I discovered that my new colleague and I had a lot in common.', 'They don’t have much in common, but they enjoy travelling together.', 'People'],
['Don’t take it personally.', 'Do not think the comment or action was aimed at you.', 'Не принимай это на свой счёт.', 'Don’t take it personally; she cancelled because she’s exhausted.', 'He disagreed with the proposal, but I didn’t take it personally.', 'Please don’t take it personally if I need some quiet time tonight.', 'People'],
['I see what you mean.', 'I understand the point you are making.', 'Я понимаю, о чём ты.', 'I see what you mean. The second route is longer but much safer.', 'Now that I’ve read the email, I see what you mean.', 'I see what you mean, but I still think we should ask first.', 'Opinions'],
['That’s not what I meant.', 'Your interpretation is different from my intention.', 'Я не это имел в виду.', 'That’s not what I meant. I was asking about the date, not the price.', 'Sorry, that’s not what I meant; let me explain it another way.', 'She thought I wanted to cancel, but that wasn’t what I meant.', 'Opinions'],
['What’s the difference?', 'Ask how two things are unlike each other.', 'В чём разница?', 'What’s the difference between these two tickets? One costs twice as much.', 'Can you explain the difference between a deposit and the full payment?', 'I tried both versions, but I couldn’t tell the difference.', 'Questions'],
['It has nothing to do with...', 'It is not connected with something.', 'Это никак не связано с...', 'It has nothing to do with you. I’m upset about something at work.', 'The delay had nothing to do with the weather.', 'That fee has nothing to do with your room; it’s for parking.', 'Problems'],
['It’s a waste of time.', 'It uses time without a useful result.', 'Это пустая трата времени.', 'It’s a waste of time calling now; their office is already closed.', 'Arguing about who was right would be a waste of time.', 'We thought the extra meeting was a waste of time until we found the error.', 'Work'],
['It takes longer than I expected.', 'It needs more time than I thought.', 'Это занимает больше времени, чем я ожидал.', 'It takes longer than I expected to get to work from the new flat.', 'The repair took longer than we expected, so we stayed another night.', 'Learning to use the software is taking longer than I expected.', 'Work'],
['I’m getting the hang of it.', 'I am starting to understand how to do it.', 'Я начинаю осваиваться.', 'I’m getting the hang of it after using the new system for a week.', 'The first lesson was confusing, but now I’m getting the hang of it.', 'Once you get the hang of the controls, parking is much easier.', 'Learning'],
['I made a mistake.', 'I did something incorrectly.', 'Я допустил ошибку.', 'I made a mistake in the booking and chose the wrong month.', 'If you make a mistake, correct it before sending the final version.', 'We all make mistakes when we try something new.', 'Problems'],
['I’ll make sure...', 'I will check or act so something definitely happens.', 'Я позабочусь о том, чтобы...', 'I’ll make sure the door is locked before we leave.', 'Please make sure everyone has the updated address.', 'We made sure we had enough time for the connection.', 'Plans'],
['Just in case.', 'To prepare for a possible situation.', 'На всякий случай.', 'I’ve downloaded the tickets just in case we lose our internet connection.', 'Take a light jacket just in case it gets cold by the sea.', 'I kept a copy of the receipt just in case.', 'Travel'],
['As soon as possible.', 'At the earliest time you reasonably can.', 'Как можно скорее.', 'Please send the corrected invoice as soon as possible.', 'I’ll book an appointment as soon as possible, but today is fully booked.', 'We need to tell the hotel as soon as possible if our flight changes.', 'Work'],
['In the meantime...', 'During the time before something else happens.', 'Тем временем...', 'The oven needs twenty minutes. In the meantime, we can prepare the salad.', 'I’ll ask the manager. In the meantime, could you wait here?', 'Your room isn’t ready yet; in the meantime, you can leave your bags with us.', 'Plans'],
['At the moment...', 'At this particular time.', 'В данный момент...', 'At the moment, I’m working on next year’s budget.', 'We don’t have that size at the moment, but it should arrive tomorrow.', 'I can’t talk at the moment. Can I call you after lunch?', 'Work'],
['So far, so good.', 'Everything has gone well up to now.', 'Пока всё хорошо.', 'So far, so good. The new routine is easier than I expected.', 'How’s the trip going? So far, so good, although it might rain tomorrow.', 'We’ve tested half the files. So far, so good.', 'Work'],
['I’m supposed to...', 'I am expected or required to do something.', 'Я должен / от меня ожидают...', 'I’m supposed to send the figures before the meeting starts.', 'Are we supposed to bring our passports to the appointment?', 'The bus was supposed to arrive at eight, but it’s still not here.', 'Work'],
['I’d rather not.', 'Politely say that you prefer not to do something.', 'Я бы предпочёл не делать этого.', 'I’d rather not drive tonight; I haven’t slept well.', 'Would you like to discuss it now? I’d rather not, if that’s okay.', 'We’d rather not book anything until our holiday dates are confirmed.', 'Choices'],
['It’s not worth the hassle.', 'The benefit is too small for the trouble involved.', 'Оно не стоит этих хлопот.', 'It’s not worth the hassle of changing trains just to save two euros.', 'We could return the broken mug, but it’s not worth the hassle.', 'I’d take a taxi with those bags; the bus isn’t worth the hassle.', 'Choices'],
['I’ll take care of it.', 'I will handle it or make the arrangements.', 'Я об этом позабочусь.', 'I’ll take care of it. You can focus on finishing your presentation.', 'Can you take care of the booking while I check the flights?', 'She took care of the paperwork before we arrived.', 'Work'],
['It’s out of my hands.', 'I no longer have control over the decision.', 'Это уже не от меня зависит.', 'It’s out of my hands now; the application is with the manager.', 'I’ve sent the documents, so the timing is out of my hands.', 'We did everything we could, but the final decision was out of our hands.', 'Work'],
['I’m a bit tied up.', 'I am busy and cannot help immediately.', 'Я сейчас немного занят.', 'I’m a bit tied up with a report. Could we talk after lunch?', 'She’s tied up in meetings all morning, but she’ll call you later.', 'We were tied up with the move and forgot to reply.', 'Work'],
['Can we work something out?', 'Ask whether we can find an acceptable solution.', 'Можем что-нибудь придумать / договориться?', 'Can we work something out? I can pay the deposit now and the rest on Friday.', 'We worked something out so both of us could take a day off.', 'Let’s work out a time that suits everyone.', 'Problems'],
['Let’s get back to...', 'Suggest returning to an earlier topic or task.', 'Давай вернёмся к...', 'Let’s get back to the main question before we run out of time.', 'After lunch, we got back to checking the figures.', 'Can we get back to planning the trip once this call is finished?', 'Work'],
['I’ll bear that in mind.', 'I will remember that when deciding or acting.', 'Я буду иметь это в виду.', 'I’ll bear that in mind when I choose the hotel.', 'Thanks for explaining the traffic situation; I’ll bear that in mind.', 'Bear in mind that the price doesn’t include breakfast.', 'Decisions']
];

export const THIRD_EXAMPLES = [
'A quiet dinner at home sounds good after such a busy week.',
'No worries if you cannot come tonight; we can meet another day.',
'I don’t mind taking the bus if parking is difficult.',
'We can cook or order something; it’s up to you tonight.',
'I have no idea where I put the receipt after we left the shop.',
'You can leave your suitcase here until five; that’s fine.',
'I’m not sure whether breakfast is included in the booking.',
'Of course you can borrow the charger; I’m not using it.',
'Was the café busy? Not really, so we got a table outside.',
'Shall we try the new bakery on Sunday? Why not?',
'Take your time choosing; the waiter said the kitchen closes at ten.',
'Here you go — I printed the tickets in case your phone battery dies.',
'I’m on my way, but the road by the station is closed.',
'Give me a minute to save the file before you turn the laptop off.',
'Would you like another slice? I’m good, thanks; dinner was lovely.',
'That’s enough water for now; we can buy more on the way.',
'It doesn’t matter if you arrive a little later; I’ll keep your food warm.',
'My bag is packed and I’m ready to leave whenever you are.',
'I have to take this call outside; see you later at the meeting.',
'Let me check the booking before we pay for another night.',
'Is the supermarket still open? I think so, but let’s check online.',
'Do we need a reservation for breakfast? I don’t think so.',
'What do you mean by an extra charge? I thought everything was included.',
'The total includes delivery, is that right? That’s right.',
'I’ll be right back; I just need to ask the receptionist for a towel.',
'Whether we drive or take the bus depends on the weather.',
'Taking the earlier flight makes sense if we want a full day there.',
'You need a quiet evening after work? Fair enough; let’s stay in.',
'My bad — I booked the table for Thursday instead of Friday.',
'A walk by the sea before breakfast? I’m down if we leave before it gets hot.',
'It’s not cheap. I mean, we would need to save for a few months.',
'Actually, the appointment is tomorrow; I checked the confirmation this morning.',
'Apparently, the new café opens at seven, so we can go before work.',
'To be honest, I’d rather spend the money on a trip than a new phone.',
'We missed the train, but at least we still have time to catch the next one.',
'As far as I know, the price includes both the ticket and the transfer.',
'The instructions are confusing, but I’ll figure it out before you get home.',
'The smaller suitcase is easier to carry; that’s the point of travelling light.',
'We missed the bus and ended up walking home along the beach.',
'It turns out the restaurant is closed on Mondays, so we need another plan.',
'I’m used to getting up early because my bus leaves just after eight.',
'I’m not used to driving on narrow mountain roads, so I’ll take it slowly.',
'We can change the reservation tomorrow; it’s not a big deal.',
'I get it — you want to rest tonight and talk about the plans tomorrow.',
'Keep the booking confirmation on your phone; you never know when you’ll need it.',
'The room costs a little more, but having a kitchen is worth it.',
'I’m just saying that checking the train times now could save us trouble later.',
'Meeting outside the station at six works for me because I finish at five.',
'I can’t make it on Saturday, but I’m free all day on Sunday.',
'The repair isn’t finished yet; I’ll keep you posted when I hear from the garage.',
'We don’t need to book the whole week now; let’s see how it goes.',
'I’m looking forward to having a few days together without work calls.',
'The name of that hotel rings a bell; I think we stayed nearby last year.',
'I need to check with my manager first, then I’ll get back to you.',
'There’s no rush to choose the menu; our friends haven’t arrived yet.',
'I’m not entirely sure whether changing suppliers would solve the delivery problem.',
'The cheapest option is always better? I’m not so sure about that.',
'Working longer means getting more done? That’s not necessarily true.',
'From my point of view, a reliable delivery date matters more than a small discount.',
'The way I see it, we should agree on the budget before choosing the destination.',
'I see where you’re coming from, but cancelling now would cost us more.',
'You’ve got a point about the noise; let’s ask for a room away from the road.',
'The apartment is small. That being said, the location would save us an hour a day.',
'For the most part, the new process is working, although a few steps need fixing.',
'For what it’s worth, I found the first week difficult too.',
'As it turns out, we could have taken the direct bus from the airport.',
'I meant to book the tickets yesterday, but it slipped my mind after work.',
'I can’t help but wonder whether we are solving the right problem.',
'The next bus is in an hour, so we might as well have lunch here.',
'I’d rather spend an extra night there than rush through the whole city.',
'It’s about time we replaced that suitcase; the handle broke on our last trip.',
'Just stop worrying about it? That’s easier said than done with a deadline tomorrow.',
'I agree the service was slow, but I wouldn’t go that far and call it terrible.',
'Why did we move twice in one year? It’s a long story; I’ll tell you over dinner.',
'Long story short, the first hotel cancelled and we found a better one nearby.',
'I’m on the fence about the early flight because it would mean leaving at three.',
'I’m leaning towards the smaller apartment because it’s closer to work.',
'The figures look unusual, but let’s not jump to conclusions before checking the source.',
'You say the walk is easy, so I’ll take your word for it and leave the hiking boots.',
'We can book a different restaurant; it’s not the end of the world.',
'The explanation is reasonable. Be that as it may, the invoice still needs correcting.',
'To put it another way, we are paying more without receiving a better service.',
'By and large, the team adapted well to the change in working hours.',
'All things considered, staying an extra night would make the trip much less stressful.',
'The delay was outside our control, but only to some extent.',
'The discount helps up to a point, but it doesn’t solve the problem with reliability.',
'As far as that goes, the proposal is clear; my concern is whether we can deliver it.',
'Who suggested it first is beside the point; we need to decide what works.',
'For all intents and purposes, the move is complete; only the internet needs connecting.',
'I’m inclined to think we should test the process with a smaller group first.',
'I wouldn’t rule it out, but moving abroad would require careful planning.',
'There’s more to it than that; a cheaper rent may come with a much longer commute.',
'That’s a fair assessment of the risks, although I would add one more concern.',
'I’m not convinced that another meeting will help unless we agree on a clear question.',
'It remains to be seen whether the new timetable will reduce the delays.',
'The wording is open to interpretation, so we should ask for a written clarification.',
'I take your point about the cost, but reliability matters to us as well.',
'I beg to differ; the smaller team delivered the project ahead of schedule.',
'Saying the whole plan has failed because of one delay is a bit of a stretch.',
'Whether a long train journey is relaxing or tiring is a matter of perspective.'
];
