// Original, level-adapted practice of IELTS skills, not official exam items.
const readings = [
  ['A2','café','At the station café, breakfast costs £6 before 10 a.m. After 10, only sandwiches are available. The café is closed on Sundays.',[
    ['You can buy breakfast at 9 a.m.','True','False|Not Given','Before 10 a.m. includes 9 a.m.','Девять утра — раньше десяти: завтрак ещё подают.'],
    ['The café opens at 7 a.m.','Not Given','True|False','The text gives no opening time.','В тексте нет времени открытия. Не придумывай недостающий факт.']]],
  ['A2','class','The beginner swimming class is on Tuesday at six. Bring a towel. You do not need to buy a ticket in advance; pay £4 at the desk.',[
    ['What should a learner bring?','A towel','A ticket bought earlier|Food for the teacher','The notice explicitly asks learners to bring a towel.','Нужно принести полотенце. Билет заранее покупать не требуется.'],
    ['The class is free.','False','True|Not Given','Learners pay £4 at the desk.','Занятие стоит четыре фунта, поэтому утверждение неверно.']]],
  ['A2','journey','Maya usually walks to work. Today it is raining, so she is taking the bus. Her office is next to the library, not the museum.',[
    ['How is Maya travelling today?','By bus','On foot|By train','Today contrasts with her usual routine.','Обычно она идёт пешком, но сегодня едет на автобусе.'],
    ['Her office is near the museum.','False','True|Not Given','The text explicitly says it is next to the library, not the museum.','В тексте прямо сказано: рядом с библиотекой, а не с музеем.']]],
  ['B1','flexible-work','A firm introduced flexible starting times for a three-month trial. Most employees welcomed the change, but the support team still had to cover the phone from nine. Managers agreed to review the arrangement after the trial.',[
    ['Which title best summarises the text?','A trial with benefits and limits','The end of all office hours|Why everyone rejected flexibility','Both support and a practical limitation are described.','В тексте есть и поддержка нововведения, и ограничение для одной команды.'],
    ['The company has made the arrangement permanent.','False','True|Not Given','It is a trial, with a review still planned.','Пока действует пробный период; постоянное решение ещё не принято.']]],
  ['B1','library','The library used to close at five. Since September it has stayed open until seven on weekdays. Weekend hours remain unchanged. Staff say students use the extra evening time, although visitor numbers have not yet been published.',[
    ['Which service has changed?','Weekday closing time','Weekend opening time|The price of membership','The two-hour extension applies to weekdays.','Дольше библиотека работает только по будням.'],
    ['Evening visitor numbers have doubled.','Not Given','True|False','No figures have been published.','Числа не опубликованы. Нельзя утверждать, что посетителей стало вдвое больше.']]],
  ['B1','travel','Leo booked an early train because it was cheaper. When it was cancelled, the company offered either a later train at no extra charge or a refund. He chose the later train because his meeting had also been delayed.',[
    ['Why did Leo accept the later train?','His meeting would start later too','He could not get a refund|The new ticket cost less','The changed meeting time made the later service suitable.','Встречу тоже перенесли, поэтому более поздний поезд ему подошёл.'],
    ['Leo had to pay extra for the later train.','False','True|Not Given','The alternative was offered at no extra charge.','Пересадку на более поздний поезд предложили без доплаты.']]],
  ['B2','transport','After a town added cycle lanes, recorded bicycle journeys increased. However, the survey was conducted in unusually dry weather and counted commuters on only three central roads. The researchers therefore cautioned against attributing the entire increase to the new infrastructure.',[
    ['What is the main limitation of the finding?','Other factors and limited coverage may affect it','No bicycle journeys were recorded|The researchers opposed all cycle lanes','Weather and a narrow sample weaken a simple causal conclusion.','Погода и узкая выборка не позволяют приписать весь рост велодорожкам.'],
    ['The new lanes were the only cause of the increase.','False','True|Not Given','The researchers explicitly warn against that interpretation.','Авторы прямо предостерегают от такого вывода.']]],
  ['B2','hybrid','A consultancy allowed staff to work remotely twice a week. Output remained stable and recruitment became easier. Nevertheless, new employees reported difficulty obtaining informal feedback. The firm retained the policy while adding weekly mentoring sessions.',[
    ['Which heading fits best?','Keeping flexibility while addressing a drawback','Returning everyone to the office|Replacing managers with software','The policy remains, with a targeted response to the feedback problem.','Гибкость сохранили, а трудность новичков решают наставничеством.'],
    ['Output increased by fifteen per cent.','False','True|Not Given','The passage says output remained stable.','Объём работы остался стабильным, а не вырос на 15%.']]],
  ['B2','packaging','Refillable containers can reduce waste, provided they are reused enough times to offset the resources needed to make and wash them. A study found that transport distance also influenced the balance. Its authors did not recommend one material for every situation.',[
    ['What condition supports the benefit of refilling?','Enough repeat use','Always using the heaviest container|Ignoring washing costs','The initial and ongoing resource costs must be offset.','Повторное использование должно компенсировать затраты на производство и мытьё.'],
    ['The authors identify a universally best material.','False','True|Not Given','They explicitly avoid a universal recommendation.','Авторы не называют один материал лучшим для любых условий.']]],
  ['C1','evaluation','The intervention coincided with a fall in staff turnover, yet comparable firms without the intervention saw a similar decline. While participants rated it positively, the evaluators argued that satisfaction data alone could not establish its effectiveness in retaining staff.',[
    ['Which inference is most defensible?','The causal effect on retention remains uncertain','Positive ratings prove the intervention worked|The intervention certainly increased turnover','A comparison group challenges attribution; satisfaction measures a different outcome.','Сходная динамика у других компаний мешает выделить эффект. Удовлетворённость и удержание — разные показатели.'],
    ['The evaluators regard satisfaction as sufficient proof of improved retention.','False','True|Not Given','Their argument explicitly rejects that sufficiency.','Оценщики прямо говорят, что одних положительных отзывов недостаточно.']]],
  ['C1','archives','Digitising an archive broadens access but does not remove the need for selection. What gets scanned, how it is described and which search terms are supported all shape what users can discover. Apparent comprehensiveness may therefore conceal persistent gaps.',[
    ['What assumption does the author challenge?','Digital availability guarantees complete access to knowledge','Archives should never be digitised|Search tools have no effect on discovery','Digitisation retains selection and discovery biases.','Оцифровка не устраняет отбор: описание и поиск тоже определяют, что удастся найти.'],
    ['The passage recommends a specific scanning resolution.','Not Given','True|False','It discusses selection and discovery, not image specifications.','Текст о доступности и отборе, а не о техническом разрешении сканирования.']]],
  ['C1','resilience','Resilience is often framed as an individual virtue. Critics of this framing do not deny the value of coping skills; rather, they question whether celebrating endurance can divert attention from avoidable organisational pressures. They advocate personal support alongside structural reform.',[
    ['Which paraphrase preserves the critics’ position?','Coping skills help, but organisational causes also need attention','Individual coping skills are entirely useless|Structural reform makes all support unnecessary','The position combines support with reform rather than rejecting either.','Авторы предлагают сочетать личную поддержку с изменением условий.'],
    ['The critics oppose every form of personal support.','False','True|Not Given','They explicitly advocate it alongside reform.','Они прямо поддерживают личную помощь вместе с реформами.']]]
];

// Authored translations of the passage itself, available even without a
// translation service. Both questions about a passage use the same text.
const passageTranslations = {
  café:'В кафе на станции завтрак стоит 6 фунтов до 10 утра. После десяти можно купить только сэндвичи. По воскресеньям кафе закрыто.',
  class:'Занятие по плаванию для начинающих проходит во вторник в шесть. Возьми полотенце. Покупать билет заранее не нужно: заплати 4 фунта на стойке.',
  journey:'Майя обычно ходит на работу пешком. Сегодня идёт дождь, поэтому она едет на автобусе. Её офис находится рядом с библиотекой, а не с музеем.',
  'flexible-work':'Компания на три месяца ввела пробный гибкий график начала рабочего дня. Большинство сотрудников поддержали изменение, но команда поддержки по-прежнему должна была отвечать на звонки с девяти. Руководители договорились пересмотреть этот порядок после пробного периода.',
  library:'Раньше библиотека закрывалась в пять. С сентября по будням она работает до семи. Расписание выходных не изменилось. Сотрудники говорят, что студенты пользуются дополнительными вечерними часами, хотя данные о числе посетителей ещё не опубликованы.',
  travel:'Лео забронировал ранний поезд, потому что он был дешевле. Когда поезд отменили, компания предложила либо более поздний поезд без доплаты, либо возврат денег. Он выбрал более поздний поезд, потому что его встречу тоже перенесли.',
  transport:'После появления велодорожек в городе число зарегистрированных поездок на велосипеде выросло. Однако исследование проводили в необычно сухую погоду и учитывали поездки на работу лишь на трёх центральных улицах. Поэтому исследователи предостерегли от того, чтобы объяснять весь рост только новой инфраструктурой.',
  hybrid:'Консалтинговая компания разрешила сотрудникам работать удалённо два раза в неделю. Объём выполненной работы остался стабильным, а нанимать людей стало проще. Тем не менее новые сотрудники сообщали, что им трудно получать неформальную обратную связь. Компания сохранила этот порядок и добавила еженедельные встречи с наставниками.',
  packaging:'Многоразовые ёмкости могут уменьшать количество отходов, если их используют достаточно раз, чтобы компенсировать ресурсы на производство и мытьё. Исследование показало, что расстояние перевозки тоже влияло на этот баланс. Авторы не рекомендовали один материал для всех ситуаций.',
  evaluation:'Внедрение программы совпало со снижением текучести кадров, однако в сопоставимых компаниях без этой программы произошло похожее снижение. Хотя участники оценивали её положительно, специалисты по оценке утверждали, что одни данные об удовлетворённости не доказывают её эффективности в удержании сотрудников.',
  archives:'Оцифровка архива расширяет доступ, но не устраняет необходимость отбора. То, что сканируют, как это описывают и какие поисковые запросы поддерживают, влияет на то, что пользователи смогут найти. Поэтому впечатление полноты может скрывать сохраняющиеся пробелы.',
  resilience:'Устойчивость к трудностям часто представляют как личное достоинство. Критики такого подхода не отрицают пользу навыков преодоления трудностей. Скорее, они задаются вопросом, не отвлекает ли восхваление выносливости от устранимого давления внутри организаций. Они выступают за поддержку людей наряду со структурными изменениями.'
};
const readingTasks = readings.flatMap(([level,slug,passage,questions]) => questions.map((row,index) => ({
  id:`ielts-${level}-${slug}-${index}`, level, skill:'Reading', taskType:row[2].includes('Not Given') ? 'True / False / Not Given' : 'Main idea & detail',
  title:level === 'A2' ? 'IELTS: первые шаги в чтении' : 'IELTS: понимание текста',
  passage, passageRu:passageTranslations[slug], prompt:row[0], answer:row[1], options:[row[1],...row[2].split('|')], explanation:row[3], ru:row[4],
  strategyEn:row[2].includes('Not Given') ? 'True agrees with the passage. False contradicts it. Not Given means the text does not tell you enough.' : 'Find the sentence that answers the question. A heading must cover the main idea, including a contrast or limitation.',
  strategyRu:row[2].includes('Not Given') ? 'True — текст подтверждает утверждение. False — текст ему противоречит. Not Given — нужного факта нет. Не добавляй сведения из своего опыта.' : 'Сначала найди в тексте нужный факт. Если выбираешь заголовок, он должен передавать главную мысль целиком, включая ограничения после but / however, а не только отдельную деталь.'
})));

const writingRows = [
  ['A2','link','I like my town _____ it is quiet.','because','but|so that|although of','Give a reason with because + subject + verb.','Причину вводим через because: дальше нужны подлежащее и сказуемое.'],
  ['A2','request','Choose a polite sentence for asking a hotel about breakfast.','Could you tell me what time breakfast starts?','Tell breakfast time now.|What breakfast is time start?|You must give breakfast.','Could you tell me introduces a polite request. The embedded question uses normal word order.','Could you tell me — вежливая просьба. Внутри вопроса порядок слов прямой.'],
  ['A2','sequence','First, boil the water. _____, add the tea.','Then','Because|Although|Unless','Then introduces the next step in a sequence.','Then обозначает следующий шаг: «затем».'],
  ['B1','overview','Sales rose from 20 to 35 units, while costs stayed the same. Choose the best summary.','Sales increased, whereas costs were unchanged.','Everything increased sharply.|Costs fell to twenty units.|Sales and costs were equal.','An overview preserves the main comparison without inventing facts.','Обобщение должно сохранять оба факта: продажи выросли, затраты не изменились.'],
  ['B1','reason','Which sentence develops an opinion with a reason?','I prefer public transport because it reduces my travel costs.','Public transport. Very good.|I prefer it. I prefer it.|Transport is transport.','A clear reason makes the opinion more useful to the reader.','После мнения объясни причину; повтор самой мысли её не раскрывает.'],
  ['B1','letter','You cannot attend an appointment. Choose a suitable opening.','I am writing to ask whether we could rearrange our appointment.','You arranged badly.|Appointment no me tomorrow.|I shall never see anyone.','State the purpose clearly and politely in a semi-formal message.','В начале письма вежливо и прямо объясни цель обращения.'],
  ['B2','overview','Car use fell from 60% to 40%; cycling rose from 10% to 25%. Which overview is accurate?','Travel shifted away from cars towards cycling.','Most people stopped travelling.|Cycling became more common than driving.|Car use halved.','Summarise the direction of change without overstating the numbers.','Передай направление изменений. Велосипеды не обогнали машины, а доля машин не сократилась вдвое.'],
  ['B2','argument','Which sentence gives a qualified argument about remote work?','Remote work can improve flexibility, although some teams need more structured communication.','Remote work is always perfect for everyone.|Nobody can work outside an office.|Remote work has absolutely no drawbacks.','A concession acknowledges a relevant limitation without abandoning the main point.','Уступка показывает ограничение, сохраняя основную мысль.'],
  ['B2','cohesion','Public transport is affordable. _____, limited evening services make it inconvenient for shift workers.','However','Therefore|For this reason|As a result','The second sentence introduces a contrasting drawback, not a result.','Во второй части — недостаток в противовес достоинству, а не следствие.'],
  ['C1','claim','A study shows correlation, but has no control group. Which conclusion is proportionate?','The findings suggest a possible association, but do not establish causation.','The study proves the policy caused the change.|The evidence is worthless in every respect.|There is certainly no relationship.','Match the certainty of the conclusion to the strength of the research design.','Сила вывода должна соответствовать качеству доказательств. Корреляция не доказывает причинность.'],
  ['C1','synthesis','Which sentence synthesises access and quality concerns?','Although wider access is desirable, expansion must be supported by adequate resources to maintain quality.','Access is good. Quality is good. Good things are good.|Quality and access cannot ever coexist.|All expansion necessarily improves standards.','A synthesis shows how the two ideas constrain or support each other.','Свяжи две идеи: расширение доступа требует ресурсов, чтобы сохранить качество.'],
  ['C1','register','Choose the most appropriate academic phrasing.','The proposal warrants further scrutiny before implementation.','This thing is totally awesome, obviously.|Everyone knows it works, end of story.|It is, like, super good stuff.','Academic writing favours precise, supported claims over emphatic informality.','Академический стиль требует точных формулировок, а не эмоционального усиления.']
];

const writingTasks = writingRows.map(([level,slug,prompt,answer,distractors,en,ru]) => ({
  id:`ielts-${level}-writing-${slug}`,level,skill:'Writing',taskType:'Sentence building',title:'IELTS: строим письменный ответ',prompt,answer,options:[answer,...distractors.split('|')],explanation:en,ru,
  strategyEn:'Make one clear point. Support it with a reason, comparison or example; avoid claims the information cannot support.',
  strategyRu:'Сформулируй одну ясную мысль. Добавь причину, сравнение или пример. Не утверждай того, чего исходные данные не подтверждают.'
}));

const speakingRows = [
  ['A2','home','Describe your home. What rooms does it have? Which room do you like?','I live in a small flat. It has two rooms. I like the kitchen because it is bright.','Назови жильё, две детали и причину предпочтения.','Describe a place → give details → say why you like it.'],
  ['A2','weekend','What do you usually do at the weekend? Talk about one thing you enjoy.','I usually go for a walk. I sometimes meet a friend. I enjoy walking because I can relax.','Расскажи о привычке и объясни, почему она тебе нравится.','Present simple + usually / sometimes + because.'],
  ['B1','skill','Describe a skill you learned. Say when you started, what was difficult and why it is useful.','I started learning to cook last year. At first, timing was difficult. Now I can prepare healthy meals, so I spend less on takeaways.','Короткая история: начало, трудность, результат.','Past experience → challenge → present benefit.'],
  ['B1','trip','Describe a journey that did not go as planned. What changed, and what did you do?','My train was cancelled, so I took a bus. Although I arrived late, I still met my friends. Next time I would leave earlier.','Опиши проблему, решение и вывод.','Past simple + so / although + a short reflection.'],
  ['B2','work','How has technology changed the way people work? Give a benefit and a drawback.','Technology allows more flexible working, which can save commuting time. However, constant messages may blur the boundary between work and home.','Сравни достоинство и недостаток, поясни каждый примером.','Claim → example → contrasting point → balanced conclusion.'],
  ['B2','cities','Should cities prioritise public transport over private cars? Explain your view and consider an objection.','I would prioritise public transport because it uses limited road space more efficiently. However, rural commuters may still need cars where services are infrequent.','Обоснуй позицию и признай разумное возражение.','Position + because → example → concession with however.'],
  ['C1','education','To what extent should education respond to the labour market rather than broader social needs?','Employment matters, yet treating education solely as vocational training risks narrowing its purpose. A balanced approach would develop transferable skills while preserving intellectual and civic goals.','Сопоставь критерии и сформулируй взвешенный вывод.','Qualified position → competing priorities → synthesis.'],
  ['C1','measurement','Does measuring performance necessarily improve it? Discuss assumptions and unintended consequences.','Measurement can clarify priorities, provided the indicators reflect meaningful outcomes. Poorly chosen targets, however, may encourage people to optimise the metric rather than the work itself.','Укажи условие полезности измерения и возможный побочный эффект.','Conditional claim → mechanism → limitation → implication.']
];
export const DAILY_IELTS = [...readingTasks,...writingTasks,...speakingRows.map(([level,slug,prompt,model,ru,structure]) => ({
  id:`ielts-${level}-speaking-${slug}`,level,skill:'Speaking',taskType:level === 'A2' ? 'Part 1 foundation' : level === 'B1' ? 'Part 2 practice' : 'Part 3 practice',
  title:'IELTS: готовим связный ответ',prompt,model,ru,structure,practice:true,seconds:level === 'A2' ? 30 : level === 'B1' ? 45 : 60,
  strategyEn:'Rehearse silently, write notes or speak aloud. Check the structure of your answer; pronunciation is not automatically assessed.',
  strategyRu:'Ответь про себя, запиши опорные слова или говори вслух, если удобно. Затем сверь структуру. Самопроверка не считается проверенным правильным ответом и не уменьшает точность.'
}))];
export const dailyIeltsForLevel = (level,skill) => DAILY_IELTS.filter(task => task.level === level && (!skill || task.skill === skill));
