// Original bilingual additions. Stable headword IDs; every example has its own translation.
const banks={
 A2:`
battery|батарея; аккумулятор|a source of electrical power|A low battery — почти разряженная батарея.|My phone battery is low.|У телефона садится батарея.|The remote needs a new battery.|Пульту нужна новая батарейка.
socket|розетка|a place to plug in electrical equipment|Plug something into a socket — включить в розетку.|There is a socket beside the bed.|Рядом с кроватью есть розетка.|This socket doesn't work.|Эта розетка не работает.
plug|вилка; штекер|the part that connects a device to power|Pull out the plug — вытащить вилку.|The plug doesn't fit this socket.|Вилка не подходит к этой розетке.|Pull out the plug before cleaning it.|Вытащи вилку перед чисткой.
screen|экран|the surface displaying images|A cracked screen — треснувший экран.|The screen is too bright.|Экран слишком яркий.|There is a crack in the screen.|На экране есть трещина.
password|пароль|a secret code for access|Enter a password — ввести пароль.|I forgot my password.|Я забыл пароль.|Please enter your password.|Пожалуйста, введи пароль.
folder|папка|a container for papers or computer files|A shared folder — общая папка.|Save the photo in this folder.|Сохрани фото в этой папке.|The documents are in the blue folder.|Документы в синей папке.
button|кнопка; пуговица|a small part you press or fasten|Press a button — нажать кнопку.|Press the green button.|Нажми зелёную кнопку.|A button is missing from my shirt.|На рубашке не хватает пуговицы.
keyboard|клавиатура|keys used to type|Type on a keyboard — печатать на клавиатуре.|This keyboard is very small.|Эта клавиатура очень маленькая.|I spilled tea on the keyboard.|Я пролил чай на клавиатуру.
headphones|наушники|a device worn over your ears|Обычно употребляется во множественном числе.|I left my headphones at home.|Я оставил наушники дома.|These headphones are comfortable.|Эти наушники удобные.
remote control|пульт|a device for controlling something from a distance|The remote — разговорное сокращение.|Where is the remote control?|Где пульт?|The remote control needs batteries.|Пульту нужны батарейки.
tap|кран|a device controlling water flow|Turn off the tap — закрыть кран. В США часто faucet.|Turn off the tap, please.|Закрой кран, пожалуйста.|The kitchen tap is leaking.|Кухонный кран протекает.
sink|раковина|a basin for washing|The kitchen sink — кухонная раковина.|The plates are in the sink.|Тарелки в раковине.|Please clean the sink.|Пожалуйста, помой раковину.
oven|духовка|an enclosed space for cooking|Put something in the oven — поставить в духовку.|The oven is still hot.|Духовка ещё горячая.|Put the cake in the oven.|Поставь пирог в духовку.
kettle|чайник|a container used to boil water|An electric kettle — электрический чайник.|Fill the kettle with water.|Налей в чайник воды.|The kettle is boiling.|Чайник закипает.
pan|сковорода; кастрюля|a metal container for cooking|A frying pan — сковорода; saucepan — кастрюля.|Heat the oil in a pan.|Разогрей масло в сковороде.|This pan is too small.|Эта сковорода слишком маленькая.
lid|крышка|the top covering a container|Put the lid on — накрыть крышкой.|Put the lid on the pan.|Накрой сковороду крышкой.|I can't open the lid.|Я не могу открыть крышку.
bowl|миска; пиала|a deep round dish|A bowl of soup — миска супа.|Put the apples in a bowl.|Положи яблоки в миску.|I'd like a bowl of soup.|Я бы хотел миску супа.
fork|вилка|a tool with points for eating|A knife and fork — нож и вилка.|Could I have a fork, please?|Можно вилку, пожалуйста?|There is a fork beside each plate.|Рядом с каждой тарелкой лежит вилка.
spoon|ложка|a tool for eating or stirring|A teaspoon — чайная ложка.|I need a spoon for the soup.|Мне нужна ложка для супа.|Add a spoon of sugar.|Добавь ложку сахара.
knife|нож|a tool with a sharp blade|Множественное число — knives.|Be careful with that knife.|Осторожнее с этим ножом.|This knife isn't sharp.|Этот нож не острый.
plate|тарелка|a flat dish for food|Wash the plates — помыть тарелки.|Your plate is on the table.|Твоя тарелка на столе.|I'll wash the plates later.|Я помою тарелки позже.
cupboard|шкаф; буфет|a storage space with doors|A kitchen cupboard — кухонный шкаф.|The cups are in the cupboard.|Чашки в шкафу.|Close the cupboard door.|Закрой дверцу шкафа.
drawer|ящик|a sliding storage compartment|The top drawer — верхний ящик.|The keys are in the top drawer.|Ключи в верхнем ящике.|This drawer won't open.|Этот ящик не открывается.
curtain|штора|fabric covering a window|Обычно curtains: open the curtains — раздвинуть шторы.|Open the curtains, please.|Раздвинь шторы, пожалуйста.|We need a longer curtain.|Нам нужна штора подлиннее.
carpet|ковёр; ковровое покрытие|a soft covering for a floor|On the carpet — на ковре.|There is a stain on the carpet.|На ковре есть пятно.|The children are sitting on the carpet.|Дети сидят на ковре.
pillow|подушка|a soft support for your head|A pillowcase — наволочка.|Could I have another pillow?|Можно ещё одну подушку?|This pillow is too soft.|Эта подушка слишком мягкая.
soap|мыло|a substance used for washing|A bar of soap — кусок мыла.|There is no soap in the bathroom.|В ванной нет мыла.|Wash your hands with soap.|Вымой руки с мылом.
toothbrush|зубная щётка|a brush for cleaning teeth|Brush your teeth — чистить зубы.|I forgot my toothbrush.|Я забыл зубную щётку.|Is this your toothbrush?|Это твоя зубная щётка?
toothpaste|зубная паста|a paste for cleaning teeth|A tube of toothpaste — тюбик пасты.|We need more toothpaste.|Нам нужна ещё зубная паста.|Put a little toothpaste on the brush.|Нанеси немного пасты на щётку.
mirror|зеркало|a surface showing your reflection|Look in the mirror — посмотреть в зеркало.|Look in the mirror before you leave.|Посмотри в зеркало перед выходом.|There is a mirror above the sink.|Над раковиной есть зеркало.
bin|мусорное ведро|a container for rubbish|Put it in the bin — выбросить в мусорное ведро.|Put the paper in the bin.|Выброси бумагу в мусорное ведро.|The bin is full.|Мусорное ведро полное.
laundry|стирка; бельё для стирки|clothes that need washing|Do the laundry — стирать.|I'll do the laundry tomorrow.|Я постираю завтра.|The laundry is still wet.|Бельё ещё мокрое.
stain|пятно|a dirty mark|A coffee stain — пятно от кофе.|There is a coffee stain on my shirt.|На рубашке пятно от кофе.|This stain won't come out.|Это пятно не отстирывается.
floor|пол; этаж|the surface you walk on or a building level|On the second floor — на втором этаже; on the floor — на полу.|The floor is wet.|Пол мокрый.|Our room is on the third floor.|Наш номер на третьем этаже.
ceiling|потолок|the top inside surface of a room|On the ceiling — на потолке.|There is a light on the ceiling.|На потолке есть светильник.|This room has a low ceiling.|В этой комнате низкий потолок.
roof|крыша|the top outside covering of a building|On the roof — на крыше.|The roof needs repair.|Крышу нужно отремонтировать.|There is snow on the roof.|На крыше лежит снег.
stairs|лестница; ступени|steps between building levels|Take the stairs — идти по лестнице.|Let's take the stairs.|Давай пойдём по лестнице.|The stairs are very narrow.|Лестница очень узкая.
lift|лифт|a device carrying people between floors|В США — elevator.|The lift is out of order.|Лифт не работает.|Take the lift to the fifth floor.|Поднимись на лифте на пятый этаж.
balcony|балкон|an outside platform attached to a building|On the balcony — на балконе.|Let's have breakfast on the balcony.|Давай позавтракаем на балконе.|The room has a small balcony.|В номере есть небольшой балкон.
gate|ворота; выход на посадку|an entrance that can be closed|В аэропорту gate — выход на посадку.|Close the gate behind you.|Закрой за собой ворота.|Our flight leaves from gate six.|Посадка на наш рейс — у выхода шесть.
fence|забор|a structure around an area|A wooden fence — деревянный забор.|The garden has a wooden fence.|Вокруг сада деревянный забор.|Don't climb over the fence.|Не перелезай через забор.
path|дорожка; тропинка|a small way for walking|Follow the path — идти по тропинке.|Follow this path to the beach.|Иди по этой дорожке к пляжу.|The path is muddy after rain.|После дождя тропинка грязная.
pavement|тротуар|the walking area beside a road|В США — sidewalk.|Walk on the pavement.|Иди по тротуару.|The pavement is icy.|На тротуаре лёд.
crossing|переход|a place for crossing a road|A pedestrian crossing — пешеходный переход.|Use the crossing near the school.|Перейди дорогу у школы по переходу.|Wait at the crossing.|Подожди у перехода.
roundabout|круговая развязка|a circular road junction|At the roundabout — на круговой развязке.|Turn left at the roundabout.|На круговой развязке поверни налево.|There is a roundabout ahead.|Впереди круговая развязка.
bridge|мост|a structure over water or a road|Cross the bridge — перейти мост.|Cross the bridge and turn right.|Перейди мост и поверни направо.|The bridge is closed today.|Сегодня мост закрыт.
station|станция; вокзал|a place where trains stop|A train station — железнодорожный вокзал.|I'll meet you at the station.|Встретимся на вокзале.|The station is ten minutes away.|До вокзала десять минут.
petrol|бензин|fuel for a car|В США — gas; petrol station — заправка.|We need to buy petrol.|Нам нужно заправиться.|The price of petrol has gone up.|Бензин подорожал.
wheel|колесо|a round part allowing movement|A steering wheel — руль.|One wheel is damaged.|Одно колесо повреждено.|Keep both hands on the steering wheel.|Держи обе руки на руле.
tyre|шина|the rubber outside of a wheel|A flat tyre — спущенное колесо.|We have a flat tyre.|У нас спустило колесо.|This tyre needs replacing.|Эту шину нужно заменить.
engine|двигатель|the part producing power|Start the engine — завести двигатель.|The engine won't start.|Двигатель не заводится.|Turn off the engine, please.|Заглуши двигатель, пожалуйста.
boot|багажник; ботинок|the storage area at the back of a car|Багажник в США — trunk. Boots также сапоги.|Put the bags in the boot.|Положи сумки в багажник.|My boots are wet.|Мои ботинки мокрые.
map|карта|a drawing of an area|On the map — на карте.|Can you show me on the map?|Можешь показать мне на карте?|This road isn't on the map.|Этой дороги нет на карте.
bakery|пекарня|a shop making and selling bread|At the bakery — в пекарне.|The bakery opens at seven.|Пекарня открывается в семь.|Let's get bread from the bakery.|Давай купим хлеб в пекарне.
pharmacy|аптека|a shop selling medicines|At the pharmacy — в аптеке.|Is there a pharmacy nearby?|Поблизости есть аптека?|The pharmacy closes at nine.|Аптека закрывается в девять.
parcel|посылка|a wrapped package sent by post|Send a parcel — отправить посылку.|A parcel arrived for you.|Для тебя пришла посылка.|I'd like to send this parcel.|Я хотел бы отправить эту посылку.
stamp|почтовая марка|a small label showing postage is paid|A stamp on an envelope — марка на конверте.|I need a stamp for this letter.|Мне нужна марка для этого письма.|Put the stamp in the top corner.|Приклей марку в верхнем углу.
envelope|конверт|a paper cover for a letter|In an envelope — в конверте.|Put the card in an envelope.|Положи открытку в конверт.|Write the address on the envelope.|Напиши адрес на конверте.
wallet|кошелёк|a small holder for money and cards|Lose your wallet — потерять кошелёк.|I left my wallet at home.|Я оставил кошелёк дома.|My card is in my wallet.|Моя карта в кошельке.
pocket|карман|a small compartment in clothing|In my pocket — у меня в кармане.|My keys are in my pocket.|Ключи у меня в кармане.|This jacket has deep pockets.|У этой куртки глубокие карманы.
scarf|шарф|fabric worn around your neck|Wear a scarf — носить шарф.|Take a scarf. It's cold outside.|Возьми шарф. На улице холодно.|This scarf is very warm.|Этот шарф очень тёплый.
gloves|перчатки|coverings for your hands|A pair of gloves — пара перчаток.|I can't find my gloves.|Я не могу найти перчатки.|Wear gloves when you clean.|Надень перчатки для уборки.
coat|пальто|a warm outer garment|Put on your coat — надеть пальто.|Hang your coat by the door.|Повесь пальто у двери.|You'll need a warm coat.|Тебе понадобится тёплое пальто.
jumper|джемпер; свитер|a warm knitted garment|В США обычно sweater.|This jumper is too big.|Этот свитер слишком большой.|I bought a wool jumper.|Я купил шерстяной свитер.
zip|молния на одежде|a fastener with interlocking teeth|В США — zipper.|The zip on my bag is broken.|Молния на сумке сломана.|Close the zip before you leave.|Застегни молнию перед выходом.
cotton|хлопок|a soft natural fibre|Made of cotton — из хлопка.|This shirt is made of cotton.|Эта рубашка из хлопка.|I prefer cotton clothes in summer.|Летом я предпочитаю хлопковую одежду.
wool|шерсть|a warm fibre from animal hair|Made of wool — из шерсти.|This blanket is made of wool.|Это одеяло из шерсти.|Wool keeps you warm.|Шерсть хорошо сохраняет тепло.
loose|свободный; неплотный|not fitting tightly|Loose clothes — свободная одежда. Не путай с lose — терять.|These trousers are too loose.|Эти брюки слишком свободные.|One screw is loose.|Один винт разболтался.
tight|тесный; тугой|fitting closely or firmly|Too tight — слишком тесный.|These shoes are too tight.|Эта обувь слишком тесная.|The lid is very tight.|Крышка очень туго закручена.
wet|мокрый|covered with water|Get wet — промокнуть.|My shoes are wet.|Моя обувь мокрая.|Don't sit on the wet bench.|Не садись на мокрую скамейку.
dry|сухой|not wet|Let it dry — дать высохнуть.|The clothes are dry now.|Одежда уже высохла.|Keep the medicine in a dry place.|Храни лекарство в сухом месте.
sharp|острый|having a cutting edge|A sharp knife — острый нож.|Use a sharp knife for the tomatoes.|Возьми острый нож для помидоров.|Be careful. The edge is sharp.|Осторожнее. Край острый.
smooth|гладкий|having an even surface|A smooth surface — гладкая поверхность.|The stone feels smooth.|Камень гладкий на ощупь.|The road is smooth here.|Здесь ровная дорога.
heavy|тяжёлый|weighing a lot|Too heavy to carry — слишком тяжёлый, чтобы нести.|This suitcase is heavy.|Этот чемодан тяжёлый.|Don't carry such heavy bags.|Не носи такие тяжёлые сумки.
light|лёгкий; свет|not heavy, or illumination|A light bag — лёгкая сумка; turn on the light — включить свет.|This bag is very light.|Эта сумка очень лёгкая.|Turn on the light, please.|Включи свет, пожалуйста.
wide|широкий|having a large distance across|A wide road — широкая дорога.|This street is very wide.|Эта улица очень широкая.|The sofa is too wide for the door.|Диван слишком широкий для дверного проёма.
narrow|узкий|having little distance across|A narrow path — узкая тропинка.|The road is narrow here.|Здесь узкая дорога.|We walked along a narrow path.|Мы шли по узкой тропинке.
deep|глубокий|extending far down|Deep water — глубокая вода.|The water is deep here.|Здесь глубокая вода.|This drawer is very deep.|Этот ящик очень глубокий.
shallow|мелкий; неглубокий|not deep|Shallow water — мелководье.|The water is shallow near the beach.|У пляжа мелко.|Use a shallow dish for the salad.|Для салата возьми неглубокую тарелку.
steep|крутой|rising or falling sharply|A steep hill — крутой холм.|This hill is very steep.|Этот холм очень крутой.|Be careful on the steep steps.|Осторожнее на крутых ступенях.
slippery|скользкий|easy to slip on|A slippery floor — скользкий пол.|The floor is slippery when wet.|Мокрый пол скользкий.|The road is slippery after rain.|После дождя дорога скользкая.
broken|сломанный|damaged and not working|Broken — о вещи; out of order — техника не работает.|The window is broken.|Окно разбито.|Don't use the broken chair.|Не пользуйся сломанным стулом.
dirty|грязный|not clean|Dirty clothes — грязная одежда.|These plates are dirty.|Эти тарелки грязные.|Leave your dirty shoes by the door.|Оставь грязную обувь у двери.
tidy|аккуратный; прибранный|neat and organised|Keep it tidy — поддерживать порядок.|Your room looks tidy.|В твоей комнате порядок.|Keep your desk tidy.|Поддерживай порядок на столе.
soft|мягкий|not hard or stiff|Soft — о ткани, подушке или звуке.|This blanket is very soft.|Это одеяло очень мягкое.|I'd like a softer pillow.|Я хотел бы подушку помягче.
hard|твёрдый; трудный|firm or difficult|Hard — твёрдый; a hard task — трудная задача.|The bread is too hard.|Хлеб слишком твёрдый.|This question is hard for me.|Этот вопрос для меня трудный.
sour|кислый|having a sharp acidic taste|A sour lemon — кислый лимон.|This apple tastes sour.|Это яблоко кислое на вкус.|The milk has gone sour.|Молоко скисло.
bitter|горький|having a strong unsweet taste|Bitter coffee — горький кофе.|This coffee is too bitter.|Этот кофе слишком горький.|Dark chocolate can be bitter.|Тёмный шоколад бывает горьким.
salty|солёный|containing or tasting of salt|Too salty — пересолено.|The soup is too salty.|Суп пересолен.|Don't eat so many salty snacks.|Не ешь столько солёных снеков.
ripe|спелый|ready to eat or pick|Ripe fruit — спелые фрукты.|These peaches are ripe.|Эти персики спелые.|Wait until the tomatoes are ripe.|Подожди, пока помидоры созреют.
raw|сырой; не приготовленный|not cooked|Raw vegetables — сырые овощи.|I like raw carrots.|Я люблю сырую морковь.|The chicken is still raw inside.|Курица внутри ещё сырая.
frozen|замороженный|kept below freezing|Frozen berries — замороженные ягоды.|We have some frozen berries.|У нас есть замороженные ягоды.|The lake is frozen.|Озеро замёрзло.
slice|ломтик; кусок|a thin flat piece|A slice of bread — ломтик хлеба.|Would you like a slice of cake?|Хочешь кусок торта?|Cut the bread into slices.|Нарежь хлеб ломтиками.
peel|чистить кожуру|to remove the outer skin|Peel a potato — почистить картофелину.|Peel the potatoes before cooking.|Почисти картофель перед готовкой.|I don't peel these apples.|Я не снимаю кожуру с этих яблок.
stir|помешивать|to move food around with a spoon|Stir the soup — помешивать суп.|Stir the soup slowly.|Медленно помешивай суп.|Stir until the sugar dissolves.|Мешай, пока сахар не растворится.
pour|наливать|to make liquid flow into something|Pour into — налить в.|Pour the milk into a cup.|Налей молоко в чашку.|Could you pour me some water?|Можешь налить мне воды?
boil|кипятить; варить|to heat liquid until it bubbles|Boil water — кипятить воду; boil potatoes — варить картофель.|Boil the water first.|Сначала вскипяти воду.|Boil the eggs for ten minutes.|Вари яйца десять минут.
fry|жарить|to cook in hot oil|Fry in a pan — жарить на сковороде.|Fry the onions until soft.|Обжарь лук до мягкости.|I usually fry eggs for breakfast.|Я обычно жарю яйца на завтрак.
roast|запекать; жарить в духовке|to cook with dry heat|Roast potatoes — картофель, запечённый в духовке.|Roast the vegetables for half an hour.|Запекай овощи полчаса.|We can roast the chicken tonight.|Сегодня вечером можем запечь курицу.
leftovers|остатки готовой еды|food left after a meal|Обычно множественное число: eat the leftovers.|Put the leftovers in the fridge.|Убери остатки еды в холодильник.|We'll have leftovers for lunch.|На обед доедим то, что осталось.
Could you move a little?|Можешь немного подвинуться?|a polite request for more space|Вежливая просьба подвинуться, например на сиденье.|Could you move a little? I need some space.|Можешь немного подвинуться? Мне нужно немного места.|Could you move a little to the left?|Можешь немного подвинуться влево?
Does this seat belong to anyone?|Это место кем-нибудь занято?|asking whether a seat is taken|Так уточняют, свободно ли место, даже если на нём лежат вещи.|Does this seat belong to anyone? I'd like to sit here.|Это место занято? Я хотел бы здесь сесть.|Does this seat belong to anyone in your group?|Это место занято кем-нибудь из вашей компании?
Could I have a napkin?|Можно мне салфетку?|a polite request for a napkin|Так просят салфетку в кафе. Could I have… — «можно мне…».|Could I have a napkin, please?|Можно мне салфетку, пожалуйста?|Could I have a napkin? I spilled some coffee.|Можно мне салфетку? Я пролил немного кофе.
Can I get this to go?|Можно это с собой?|asking for takeaway food|To go — «с собой», когда заказываешь еду или напиток.|Can I get this to go? I'm in a hurry.|Можно это с собой? Я спешу.|Can I get this coffee to go?|Можно этот кофе с собой?
Do you have this in a smaller size?|У вас есть это в меньшем размере?|asking for a smaller clothing size|Готовая просьба в магазине одежды. Smaller — «меньше».|Do you have this in a smaller size? It's too loose.|У вас есть это в меньшем размере? Оно слишком свободное.|Do you have this jacket in a smaller size?|У вас есть эта куртка в меньшем размере?
The zip is broken.|Молния сломана.|saying that a zip does not work|Zip — застёжка-молния в британском английском; zipper — в американском.|The zip is broken. I can't close the bag.|Молния сломана. Я не могу закрыть сумку.|The zip on my jacket is broken.|Молния на моей куртке сломана.
Could you wrap it, please?|Можете это упаковать, пожалуйста?|asking someone to wrap an item|Так просят упаковать покупку, например подарок.|Could you wrap it, please? It's a gift.|Можете это упаковать, пожалуйста? Это подарок.|Could you wrap it in blue paper, please?|Можете упаковать это в синюю бумагу, пожалуйста?
Can I charge my phone here?|Можно здесь зарядить телефон?|asking to use a power socket|Charge my phone — «зарядить телефон».|Can I charge my phone here? The battery is low.|Можно здесь зарядить телефон? Батарея почти разрядилась.|Can I charge my phone here while I wait?|Можно здесь зарядить телефон, пока я жду?
Which platform does it leave from?|С какой платформы он отправляется?|asking about a train's departure platform|О поезде или электричке: leave from a platform — «отправляться с платформы».|Which platform does it leave from? I can't see the sign.|С какой платформы он отправляется? Я не вижу указатель.|Which platform does the airport train leave from?|С какой платформы отправляется поезд до аэропорта?
I missed my stop.|Я проехал свою остановку.|saying you failed to get off at the right stop|Не успел выйти, а транспорт поехал дальше. Miss my stop — «проехать остановку».|I missed my stop because I was reading.|Я проехал свою остановку, потому что читал.|I missed my stop, so I had to walk back.|Я проехал свою остановку, поэтому пришлось идти обратно пешком.
Can you save me a seat?|Можешь занять мне место?|asking someone to keep a seat free|Save someone a seat — «занять место для кого-то».|Can you save me a seat? I'll be there soon.|Можешь занять мне место? Я скоро буду.|Can you save me a seat near the window?|Можешь занять мне место у окна?
Could you leave the door open?|Можешь оставить дверь открытой?|asking someone not to close a door|Leave something open — «оставить что-то открытым».|Could you leave the door open? It's hot in here.|Можешь оставить дверь открытой? Здесь жарко.|Could you leave the kitchen door open?|Можешь оставить дверь на кухню открытой?
I have run out of milk.|У меня закончилось молоко.|saying there is no milk left|Run out of — «израсходовать всё». I've = I have.|I've run out of milk, so I'll go to the shop.|У меня закончилось молоко, поэтому я пойду в магазин.|I've run out of milk. Could you buy some?|У меня закончилось молоко. Можешь купить немного?
I would rather stay in.|Я бы предпочёл остаться дома.|preferring to spend time at home|Stay in — «остаться дома». I'd rather… — «я бы предпочёл…».|I'd rather stay in tonight. I'm tired.|Я бы предпочёл остаться дома сегодня вечером. Я устал.|I'd rather stay in and cook dinner.|Я бы предпочёл остаться дома и приготовить ужин.
There is no hurry.|Спешить некуда.|saying there is no need to rush|Так успокаивают: времени достаточно. There's = there is.|There's no hurry. We have plenty of time.|Спешить некуда. У нас достаточно времени.|There's no hurry to make a decision.|С решением можно не спешить.
That smells good.|Как вкусно пахнет!|reacting to a pleasant smell|О приятном запахе еды; good описывает запах, а не качество готовки.|That smells good. What are you cooking?|Как вкусно пахнет! Что ты готовишь?|That soup smells good. Can I try some?|Этот суп вкусно пахнет. Можно попробовать?
I will do the washing-up.|Я помою посуду.|offering to wash the dishes|Do the washing-up — «мыть посуду» в британском английском. I'll = I will.|I'll do the washing-up if you cook.|Я помою посуду, если ты приготовишь еду.|I'll do the washing-up after dinner.|Я помою посуду после ужина.
Can you give me a lift?|Можешь меня подвезти?|asking someone to drive you somewhere|Give someone a lift — «подвезти кого-то»; в США часто говорят a ride.|Can you give me a lift to the station?|Можешь подвезти меня до станции?|Can you give me a lift? My car won't start.|Можешь меня подвезти? Моя машина не заводится.
Could you speak up a little?|Можешь говорить немного громче?|a polite request to speak more loudly|Speak up — «говорить громче», когда плохо слышно.|Could you speak up a little? I can't hear you.|Можешь говорить немного громче? Я тебя не слышу.|Could you speak up a little? It's noisy here.|Можешь говорить немного громче? Здесь шумно.
I will be right back.|Я сейчас вернусь.|saying you will return very soon|Be right back — «сейчас вернуться». Right здесь подчёркивает, что ненадолго.|I'll be right back. I need to get my coat.|Я сейчас вернусь. Мне нужно взять пальто.|I'll be right back after I make a quick call.|Я сейчас вернусь, как только быстро позвоню.
`,
 B1:`
overdue|просроченный|later than the required date|An overdue payment — просроченный платёж.|The payment is overdue.|Платёж просрочен.|This library book is overdue.|Срок возврата этой библиотечной книги прошёл.
renew|продлевать|to make something valid again|Renew a contract — продлить договор.|I need to renew my passport.|Мне нужно обновить паспорт.|We decided to renew the contract.|Мы решили продлить договор.
charge|взимать плату; заряжать|to ask for payment or add electrical power|Charge for a service — брать плату за услугу.|They charge extra for delivery.|Они берут доплату за доставку.|I need to charge my phone.|Мне нужно зарядить телефон.
fee|плата; сбор|money paid for a particular service|An entrance fee — плата за вход.|Is there an entrance fee?|За вход нужно платить?|The bank charged a small fee.|Банк взял небольшую комиссию.
fault|неисправность; вина|a problem or responsibility for a mistake|My fault — моя вина; an electrical fault — электрическая неисправность.|There is a fault in the heating system.|В системе отопления неисправность.|It wasn't your fault.|Это была не твоя вина.
leak|протечка; утечка|liquid escaping through a hole|A water leak — протечка воды.|There is a leak under the sink.|Под раковиной протечка.|The bottle has a small leak.|Бутылка немного протекает.
blocked|заблокированный; засорённый|prevented from moving or working|A blocked drain — засорённый слив.|The drain is blocked.|Слив засорился.|My bank card has been blocked.|Мою банковскую карту заблокировали.
drain|слив; водосток|a passage carrying water away|Water goes down the drain — вода уходит в слив.|The shower drain needs cleaning.|Слив в душе нужно почистить.|Don't pour oil down the drain.|Не выливай масло в слив.
maintenance|обслуживание; уход|work keeping something in good condition|Regular maintenance — регулярное обслуживание.|The lift is closed for maintenance.|Лифт закрыт на обслуживание.|The car needs regular maintenance.|Машине нужно регулярное обслуживание.
warranty|гарантия на товар|a promise to repair a faulty product|Under warranty — на гарантии.|Is the phone still under warranty?|Телефон ещё на гарантии?|The warranty lasts two years.|Гарантия действует два года.
invoice|счёт на оплату|a document requesting payment|Invoice — счёт на оплату. Receipt — чек, подтверждающий уже совершённую оплату.|Could you send me the invoice?|Можешь прислать мне счёт?|The invoice includes delivery.|В счёт включена доставка.
purchase|покупка; приобретать|buying something|Proof of purchase — подтверждение покупки.|Keep your proof of purchase.|Сохрани подтверждение покупки.|I'm happy with this purchase.|Я доволен этой покупкой.
exchange|обменивать; обмен|to replace one thing with another|Exchange something for — обменять на.|Can I exchange this for a larger size?|Можно обменять это на больший размер?|We need to exchange some money.|Нам нужно обменять немного денег.
stock|запас; наличие товара|goods available for sale|In stock — в наличии; out of stock — нет в наличии.|This model is out of stock.|Этой модели нет в наличии.|Do you have it in stock?|Это есть в наличии?
label|этикетка; ярлык|a small piece of information attached to something|Read the label — прочитать этикетку.|Read the label before washing it.|Прочитай этикетку перед стиркой.|The price label is missing.|Ценник отсутствует.
brand|бренд; марка|the name identifying a product|A clothing brand — марка одежды.|Which brand do you prefer?|Какую марку ты предпочитаешь?|I've never tried this brand.|Я никогда не пробовал эту марку.
fabric|ткань|material used for clothing|A soft fabric — мягкая ткань.|This fabric feels rough.|Эта ткань шершавая на ощупь.|The fabric dries quickly.|Эта ткань быстро сохнет.
fit|подходить по размеру|to be the right size or shape|Fit — по размеру; suit — идти человеку.|These shoes don't fit me.|Эта обувь мне не подходит по размеру.|Will this table fit in the kitchen?|Этот стол поместится на кухне?
suit|идти; подходить|to be suitable for a person|A colour suits you — цвет тебе идёт.|That colour really suits you.|Этот цвет тебе очень идёт.|Friday doesn't suit me.|Пятница мне не подходит.
damage|повреждение; повреждать|harm making something less useful|Damage обычно неисчисляемое: some damage.|The storm caused serious damage.|Буря причинила серьёзный ущерб.|Don't damage the original document.|Не повреди оригинал документа.
scratch|царапина; царапать|a thin mark made by a sharp object|A scratch on the screen — царапина на экране.|There is a scratch on the screen.|На экране есть царапина.|The cat scratched the sofa.|Кошка поцарапала диван.
dent|вмятина|a hollow mark caused by a hit|A dent in a car door — вмятина на дверце машины.|There is a dent in the door.|На дверце вмятина.|The parcel arrived with a dent in the box.|Посылка пришла с помятой коробкой.
receipt number|номер чека|the identifier printed on a receipt|Нужен для возврата или поиска покупки.|Please enter the receipt number.|Введи номер чека.|The receipt number is at the bottom.|Номер чека указан внизу.
spare|запасной|kept for use when needed|A spare key — запасной ключ.|Do you have a spare key?|У тебя есть запасной ключ?|Take a spare battery with you.|Возьми с собой запасную батарейку.
replacement|замена|something used instead of a damaged item|A replacement part — запасная деталь.|They sent a replacement the next day.|На следующий день они прислали замену.|We need a replacement part.|Нам нужна запасная деталь.
storage|хранение; место для хранения|space or a system for keeping things|Storage space — место для хранения.|My phone has no storage left.|В памяти телефона не осталось места.|The flat needs more storage.|В квартире нужно больше места для хранения.
attachment|вложение|a file included with a message|An email attachment — вложение в письмо.|The details are in the attachment.|Подробности во вложении.|I forgot to add the attachment.|Я забыл добавить вложение.
update|обновление; обновлять|a change making something current|An update on something — свежая информация о чём-то.|The app needs an update.|Приложению нужно обновление.|Could you give me an update?|Можешь сообщить, что нового?
backup|резервная копия|an extra copy kept for safety|Make a backup — сделать резервную копию.|Make a backup before you change anything.|Сделай резервную копию перед изменениями.|The backup is saved on another drive.|Резервная копия сохранена на другом диске.
settings|настройки|options controlling how something works|Обычно множественное число.|You can change this in the settings.|Это можно изменить в настройках.|Check your privacy settings.|Проверь настройки конфиденциальности.
connection|соединение; связь|a link between devices or people|A weak connection — слабая связь.|The internet connection is weak.|Интернет-соединение слабое.|I lost the connection during the call.|Во время звонка пропала связь.
signal|сигнал|a message or radio transmission|No signal — нет сигнала.|There is no signal in the tunnel.|В тоннеле нет сигнала.|The signal is better near the window.|У окна сигнал лучше.
coverage|покрытие; охват|the area served by a network|Mobile coverage — покрытие мобильной связи.|Mobile coverage is poor here.|Здесь плохое покрытие мобильной связи.|Check the insurance coverage.|Проверь, что покрывает страховка.
outage|отключение; перебой|a period when a service stops working|A power outage — отключение электричества.|There was a power outage last night.|Вчера вечером отключили электричество.|The outage lasted an hour.|Перебой длился час.
shortcut|короткий путь; ярлык|a quicker way or a computer link|Take a shortcut — срезать путь.|We can take a shortcut through the park.|Мы можем срезать путь через парк.|Create a shortcut on your desktop.|Создай ярлык на рабочем столе.
detour|объезд; обход|a longer route avoiding a problem|Take a detour — поехать в объезд.|We had to take a detour.|Нам пришлось ехать в объезд.|The detour added twenty minutes.|Объезд добавил двадцать минут.
pedestrian|пешеход|a person travelling on foot|A pedestrian area — пешеходная зона.|Drivers must watch for pedestrians.|Водители должны следить за пешеходами.|This is a pedestrian street.|Это пешеходная улица.
fare|стоимость проезда|money paid for a journey|A bus fare — стоимость поездки на автобусе.|How much is the bus fare?|Сколько стоит проезд на автобусе?|The fare includes one bag.|В стоимость проезда входит одна сумка.
transfer|пересадка; перевод|moving to another service or account|Airport transfer — трансфер из аэропорта; bank transfer — банковский перевод.|The journey includes one transfer.|В поездке будет одна пересадка.|I made a bank transfer this morning.|Утром я сделал банковский перевод.
boarding pass|посадочный талон|a document allowing you onto a plane|Show your boarding pass — показать посадочный талон.|Have your boarding pass ready.|Подготовь посадочный талон.|My boarding pass is on my phone.|Посадочный талон у меня в телефоне.
aisle|проход между рядами|a passage between rows of seats or shelves|An aisle seat — место у прохода.|I'd prefer an aisle seat.|Я бы предпочёл место у прохода.|The bread is in the next aisle.|Хлеб в следующем проходе.
departure|отправление; вылет|the act of leaving|Departure time — время отправления.|The departure time has changed.|Время отправления изменилось.|Check the departure board.|Проверь табло вылетов.
arrival|прибытие; прилёт|the act of reaching a place|On arrival — по прибытии.|We'll call you on arrival.|Мы позвоним тебе по прибытии.|What is your arrival time?|Во сколько ты прибываешь?
layover|пересадка с ожиданием|a stop between flights|A two-hour layover — двухчасовая пересадка.|We have a long layover in Istanbul.|У нас долгая пересадка в Стамбуле.|The layover lasts three hours.|Пересадка длится три часа.
valid|действительный|officially acceptable or usable|Valid until — действителен до.|This ticket is valid for one day.|Этот билет действителен один день.|Is your passport still valid?|Твой паспорт ещё действителен?
expired|с истёкшим сроком|no longer valid because time has passed|An expired passport — паспорт с истёкшим сроком действия.|My visa has expired.|Срок действия моей визы истёк.|Don't use an expired card.|Не пользуйся картой с истёкшим сроком действия.
reschedule|переносить на другое время|to change the planned time|Reschedule an appointment — перенести приём.|Can we reschedule our meeting?|Можем перенести нашу встречу?|I need to reschedule my appointment.|Мне нужно перенести мой приём.
availability|наличие; доступность|whether something is available|Check availability — проверить наличие свободных мест.|I'll check the room availability.|Я проверю наличие свободных номеров.|Please confirm your availability.|Подтверди, когда ты сможешь участвовать.
overlap|пересечение; совпадать по времени|to cover part of the same area or time|Two meetings overlap — время двух встреч пересекается.|These meetings overlap.|Эти встречи совпадают по времени.|There is some overlap between the tasks.|Эти задачи частично пересекаются.
clash|конфликт; совпадение по времени|a conflict between plans or people|A scheduling clash — накладка в расписании.|The lesson clashes with my shift.|Урок совпадает по времени с моей сменой.|We need to avoid a clash.|Нам нужно избежать накладки.
errand|поручение; небольшое дело|a short trip to do a practical task|Run errands — ходить по делам.|I have a few errands to run.|Мне нужно сделать несколько дел.|Could you run an errand for me?|Можешь выполнить для меня одно поручение?
chore|домашняя обязанность|a routine task around the home|Household chores — домашние дела.|We share the household chores.|Мы делим домашние обязанности.|Washing dishes is my least favourite chore.|Больше всего из домашних дел я не люблю мыть посуду.
mess|беспорядок|an untidy or confused state|Make a mess — устроить беспорядок.|The kitchen is a mess.|На кухне беспорядок.|Sorry, I made a mess.|Извини, я всё тут испачкал.
clutter|лишние вещи; захламлённость|too many things in a space|Clear the clutter — убрать лишние вещи.|Let's clear the clutter from the desk.|Давай уберём со стола лишние вещи.|Too much clutter makes the room feel small.|Из-за лишних вещей комната кажется маленькой.
dispose|утилизировать; избавляться|to get rid of something|Dispose of — всегда с of.|How should I dispose of old batteries?|Как утилизировать старые батарейки?|Please dispose of the packaging safely.|Пожалуйста, безопасно утилизируй упаковку.
recycle|перерабатывать вторсырьё|to use waste materials again|Recycle paper — сдавать бумагу на переработку.|We recycle paper and plastic.|Мы сдаём бумагу и пластик на переработку.|Can this bottle be recycled?|Эту бутылку можно переработать?
sorting|сортировка|putting things into groups|Waste sorting — раздельный сбор отходов.|Waste sorting is easier with separate bins.|Раздельный сбор проще с отдельными контейнерами.|I'm sorting the documents by date.|Я сортирую документы по дате.
ingredient|ингредиент|one component used in a dish|An ingredient in a recipe — ингредиент в рецепте.|We have all the ingredients.|У нас есть все ингредиенты.|What is the main ingredient?|Какой главный ингредиент?
portion|порция|an amount of food for one person|A generous portion — большая порция.|The portions here are generous.|Здесь большие порции.|I'd like a smaller portion.|Я хотел бы порцию поменьше.
appetite|аппетит|the desire to eat|Lose your appetite — потерять аппетит.|I have no appetite today.|У меня сегодня нет аппетита.|That walk gave me an appetite.|После прогулки у меня появился аппетит.
craving|сильное желание чего-то|a strong desire for a particular thing|A craving for sweets — тяга к сладкому.|I have a craving for chocolate.|Мне очень хочется шоколада.|The craving usually passes quickly.|Обычно это сильное желание быстро проходит.
balanced|сбалансированный|containing a sensible mixture|A balanced diet — сбалансированное питание.|I try to eat a balanced diet.|Я стараюсь питаться сбалансированно.|We need a balanced view of the problem.|Нам нужен взвешенный взгляд на проблему.
roughly|примерно|approximately|Roughly ten minutes — примерно десять минут.|It takes roughly half an hour.|Это занимает примерно полчаса.|There are roughly fifty people here.|Здесь примерно пятьдесят человек.
barely|едва; почти не|only just or almost not|Barely enough — едва хватает.|I can barely hear you.|Я тебя едва слышу.|We barely had time for breakfast.|У нас едва хватило времени на завтрак.
nearly|почти|almost|Nearly missed — чуть не пропустил.|I nearly missed the bus.|Я чуть не опоздал на автобус.|The work is nearly finished.|Работа почти закончена.
frequently|часто|on many occasions|Более нейтрально и формально, чем often.|This bus runs frequently.|Этот автобус ходит часто.|I frequently forget where I put my keys.|Я часто забываю, куда положил ключи.
occasionally|изредка; иногда|sometimes but not often|Случается время от времени.|We occasionally eat out.|Мы изредка едим вне дома.|I occasionally work from home.|Я иногда работаю из дома.
gradually|постепенно|little by little|Gradually improve — постепенно улучшаться.|My English is gradually improving.|Мой английский постепенно улучшается.|The weather gradually got colder.|Погода постепенно становилась холоднее.
rough|примерный; грубый|not exact or not smooth|A rough estimate — приблизительная оценка.|Give me a rough estimate.|Дай мне приблизительную оценку.|The road is rough here.|Здесь неровная дорога.
accurately|точно; без ошибок|in a correct and exact way|Describe accurately — описать точно.|Please enter the details accurately.|Пожалуйста, введи данные без ошибок.|It's hard to predict accurately.|Точно предсказать трудно.
straightforward|простой; понятный|easy to understand or do|A straightforward process — понятная процедура.|The instructions are straightforward.|Инструкции понятные.|It was a straightforward question.|Это был простой вопрос.
awkward|неловкий; неудобный|uncomfortable or difficult to deal with|An awkward moment — неловкий момент.|There was an awkward silence.|Повисла неловкая тишина.|This box is awkward to carry.|Эту коробку неудобно нести.
hesitate|колебаться; медлить|to pause because you are unsure|Don't hesitate to ask — не стесняйся спросить.|Don't hesitate to ask for help.|Не стесняйся просить помощи.|She hesitated before replying.|Она помедлила перед ответом.
hesitant|нерешительный; сомневающийся|unsure about doing something|Hesitant about — сомневаться насчёт.|I'm hesitant about signing this.|Я сомневаюсь, стоит ли это подписывать.|He sounded hesitant on the phone.|По телефону он говорил неуверенно.
eager|очень заинтересованный; стремящийся|wanting something very much|Eager to do — с большим желанием сделать.|I'm eager to learn more.|Я очень хочу узнать больше.|The children were eager to leave.|Детям не терпелось уйти.
stubborn|упрямый|unwilling to change your mind|О человеке; иногда о стойкой проблеме.|He can be very stubborn.|Он бывает очень упрямым.|This is a stubborn stain.|Это въевшееся пятно.
thoughtful|внимательный; заботливый|showing care or careful thought|That's thoughtful of you — как заботливо с твоей стороны.|That was a thoughtful gift.|Это был подарок, выбранный с заботой.|She's thoughtful towards her colleagues.|Она внимательно относится к коллегам.
generous|щедрый|willing to give or share|Generous with your time — щедро уделять время.|Thank you for your generous offer.|Спасибо за твоё щедрое предложение.|She's generous with her time.|Она охотно уделяет другим своё время.
genuine|настоящий; искренний|real rather than false|A genuine apology — искреннее извинение.|That sounds like a genuine apology.|Похоже на искреннее извинение.|Is this genuine leather?|Это натуральная кожа?
curious|любопытный|wanting to know more|Curious about — интересующийся чем-то.|I'm curious about how it works.|Мне интересно, как это работает.|The children are naturally curious.|Дети от природы любопытны.
catch up|наверстать; пообщаться после перерыва|reach the same point or exchange news|Catch up with work — наверстать работу; with a friend — пообщаться.|I need to catch up with my work.|Мне нужно наверстать работу.|Let's catch up over coffee.|Давай встретимся за кофе и поболтаем.
drop off|завезти; оставить по пути|take someone or something to a place|Drop someone off — подвезти и высадить.|Can you drop me off at the station?|Можешь подвезти меня до вокзала?|I'll drop off the keys tomorrow.|Я завезу ключи завтра.
pick up|забрать; подобрать|collect someone or something|Pick someone up — заехать за человеком.|I'll pick you up at six.|Я заеду за тобой в шесть.|Can you pick up the parcel?|Можешь забрать посылку?
run into|случайно встретить; столкнуться с|meet unexpectedly or encounter a problem|Run into someone — встретить случайно.|I ran into an old colleague.|Я случайно встретил бывшего коллегу.|We ran into a small problem.|Мы столкнулись с небольшой проблемой.
sort out|разобраться; привести в порядок|solve a problem or organise things|Sort it out — решить вопрос.|Let's sort out the details.|Давай разберёмся с деталями.|I need to sort out my documents.|Мне нужно привести документы в порядок.
put off|откладывать|delay doing something|Put off doing — откладывать действие.|Don't put off booking the tickets.|Не откладывай покупку билетов.|We had to put off the meeting.|Нам пришлось отложить встречу.
show up|появиться; прийти|arrive at a place or event|Разговорное: show up late — опоздать.|He didn't show up for the meeting.|Он не пришёл на встречу.|What time should we show up?|Во сколько нам прийти?
turn down|отказать; убавить|refuse or reduce the volume|Turn down an offer — отклонить предложение.|She turned down the offer.|Она отказалась от предложения.|Could you turn down the music?|Можешь сделать музыку потише?
take over|взять на себя; сменить|start doing another person's task|Take over from someone — сменить человека.|Can you take over for ten minutes?|Можешь меня сменить на десять минут?|She took over the project in June.|Она возглавила проект в июне.
look into|изучить; разобраться в|investigate or check a matter|Look into an issue — изучить вопрос.|I'll look into the problem.|Я разберусь с проблемой.|We're looking into cheaper options.|Мы изучаем более дешёвые варианты.
get along|ладить|have a friendly relationship|Get along with someone — ладить с кем-то.|I get along with my neighbours.|Я лажу с соседями.|Do your children get along?|Твои дети ладят между собой?
get by|справляться; обходиться|manage with limited resources|Get by on — обходиться определённой суммой.|We can get by without a car.|Мы можем обойтись без машины.|It's hard to get by on this salary.|На такую зарплату трудно прожить.
come across|наткнуться; случайно встретить|find something by chance|Come across a word — встретить слово.|I came across an interesting article.|Я наткнулся на интересную статью.|Have you come across this word before?|Ты встречал это слово раньше?
figure out|понять; разобраться|understand or find a solution|Figure out how — понять, как.|I can't figure out how to open it.|Я не могу понять, как это открыть.|We figured out what went wrong.|Мы разобрались, что пошло не так.
hang on|подождать|wait briefly|Разговорное: hang on a second.|Hang on, I'll get my keys.|Подожди, я возьму ключи.|Can you hang on for a minute?|Можешь подождать минуту?
hold on|подождать; держаться|wait or keep a grip|Hold on to something — держаться за что-то.|Hold on, I'm coming.|Подожди, я иду.|Hold on to the handrail.|Держись за поручень.
let someone know|сообщить кому-то|give someone information|Let me know — сообщи мне.|Let me know when you arrive.|Сообщи мне, когда приедешь.|I'll let you know tomorrow.|Я сообщу тебе завтра.
give someone a hand|помочь кому-то|help with a practical task|Give me a hand — помоги мне.|Could you give me a hand with this box?|Можешь помочь мне с этой коробкой?|I'll give you a hand after lunch.|Я помогу тебе после обеда.
be running late|опаздывать|be behind the planned time|I'm running late — я опаздываю.|I'm running late, so don't wait.|Я опаздываю, поэтому не жди.|We're running late for the train.|Мы опаздываем на поезд.
make up your mind|решиться; принять решение|decide after considering options|Make up my mind — принять решение самому.|I can't make up my mind.|Я не могу решиться.|Have you made up your mind yet?|Ты уже принял решение?
`,
 B2:`
contested|оспариваемый|disputed by different sides|A contested claim — оспариваемое утверждение.|The figure is still contested.|Эту цифру всё ещё оспаривают.|This is a contested interpretation.|Это спорная трактовка.
alignment|согласованность|agreement between aims or plans|Alignment with — соответствие чему-то.|We need better alignment between the teams.|Нам нужна лучшая согласованность между командами.|The plan is in alignment with our goals.|План соответствует нашим целям.
disruption|нарушение работы; сбой|an interruption to normal activity|Minimise disruption — свести перебои к минимуму.|The repairs caused some disruption.|Ремонт вызвал некоторые перебои.|We want to minimise disruption to passengers.|Мы хотим свести неудобства для пассажиров к минимуму.
drift|смещение; уход от цели|a gradual movement away|A drift in priorities — постепенное смещение приоритетов.|We noticed a drift in the schedule.|Мы заметили, что сроки постепенно сдвигаются.|Don't let the discussion drift off topic.|Не позволяй обсуждению уходить от темы.
contingent|зависящий от условия|dependent on something happening|Contingent on — зависит от выполнения условия.|Approval is contingent on the budget.|Одобрение зависит от бюджета.|The offer is contingent on a successful inspection.|Предложение действует при условии успешной проверки.
redundant|избыточный; сокращённый|unnecessary or no longer employed|Redundant information — лишняя информация; made redundant — сокращён.|Remove the redundant information.|Убери лишнюю информацию.|Several positions were made redundant.|Несколько должностей сократили.
comprehensive|полный; всесторонний|covering all important aspects|Comprehensive — не «понятный», а всеобъемлющий.|We need a comprehensive review.|Нам нужен всесторонний анализ.|The guide is comprehensive but readable.|Руководство полное, но легко читается.
preliminary|предварительный|done before the main activity|Preliminary results — предварительные результаты.|These are only preliminary results.|Это лишь предварительные результаты.|We held a preliminary discussion.|Мы провели предварительное обсуждение.
underlying|лежащий в основе|existing beneath an apparent problem|The underlying cause — первопричина.|We need to find the underlying cause.|Нам нужно найти первопричину.|The underlying problem hasn't changed.|Основная проблема не изменилась.
adverse|неблагоприятный|harmful or unfavourable|Adverse effects — неблагоприятные последствия.|The weather had an adverse effect on travel.|Погода неблагоприятно повлияла на поездки.|There were no adverse reactions.|Нежелательных реакций не было.
prone|склонный; подверженный|likely to experience something bad|Prone to errors — подверженный ошибкам.|This process is prone to errors.|В этом процессе часто возникают ошибки.|The area is prone to flooding.|Эта территория подвержена наводнениям.
adequate|достаточный; приемлемый|enough for a purpose|Adequate for — достаточный для.|Do we have adequate resources?|Достаточно ли у нас ресурсов?|The room was adequate for one night.|Для одной ночи номер был вполне приемлемым.
insufficient|недостаточный|not enough for a purpose|Insufficient evidence — недостаточно доказательств.|The available evidence is insufficient.|Имеющихся доказательств недостаточно.|There was insufficient time to check everything.|Времени на полную проверку не хватило.
subsequent|последующий|happening after something else|Subsequent changes — последующие изменения.|Subsequent checks found no errors.|При последующих проверках ошибок не нашли.|The rule changed in subsequent years.|В последующие годы правило изменилось.
ongoing|продолжающийся; текущий|still happening|An ongoing investigation — продолжающееся расследование.|The discussion is ongoing.|Обсуждение продолжается.|We provide ongoing support.|Мы предоставляем постоянную поддержку.
pending|ожидающий решения|not yet resolved or completed|Pending approval — ожидает одобрения.|The request is pending approval.|Запрос ожидает одобрения.|Two issues are still pending.|Два вопроса всё ещё не решены.
binding|обязательный к исполнению|creating an obligation|A legally binding agreement — юридически обязательное соглашение.|Is this agreement binding?|Это соглашение обязательно к исполнению?|The decision is binding on both sides.|Решение обязательно для обеих сторон.
compliance|соблюдение требований|following rules or requirements|Compliance with — соблюдение чего-то.|We checked compliance with the rules.|Мы проверили соблюдение правил.|The changes improve compliance.|Изменения улучшают соблюдение требований.
exemption|освобождение от требования|permission not to follow a usual rule|An exemption from a fee — освобождение от сбора.|Students can apply for an exemption.|Студенты могут подать заявку на освобождение.|There is no exemption from this requirement.|Исключений из этого требования нет.
eligibility|соответствие условиям|meeting conditions for something|Check eligibility — проверить право на участие.|Check your eligibility before applying.|Проверь, соответствуешь ли ты условиям, перед подачей заявки.|Eligibility depends on your circumstances.|Право на участие зависит от твоих обстоятельств.
touch base|коротко связаться; свериться|contact someone briefly to exchange updates|Touch base with someone — коротко связаться с кем-то.|Let's touch base on Monday.|Давай коротко свяжемся в понедельник.|I'll touch base with the team tomorrow.|Завтра я сверюсь с командой.
keep someone in the loop|держать кого-то в курсе|include someone in updates|Keep me in the loop — держи меня в курсе.|Please keep me in the loop.|Пожалуйста, держи меня в курсе.|We should keep Anna in the loop.|Нам стоит держать Аню в курсе.
rule out|исключить вариант|decide something is not possible|Rule out a cause — исключить причину.|We can't rule out a delay.|Мы не можем исключить задержку.|The tests ruled out that explanation.|Проверки исключили это объяснение.
iron out|устранить небольшие проблемы|resolve remaining difficulties|Iron out the details — согласовать детали.|We still need to iron out the details.|Нам ещё нужно согласовать детали.|Let's iron out the remaining issues.|Давай устраним оставшиеся проблемы.
follow through|довести до конца|complete what you committed to do|Follow through on a promise — выполнить обещание.|We need to follow through on this plan.|Нам нужно довести этот план до конца.|She always follows through on her promises.|Она всегда выполняет свои обещания.
phase out|постепенно выводить из использования|stop using something gradually|Phase out an old system — постепенно отказаться от старой системы.|We're phasing out the old software.|Мы постепенно отказываемся от старого ПО.|The service will be phased out next year.|В следующем году сервис постепенно закроют.
scale up|увеличить масштаб|increase the size of an activity|Scale up production — увеличить производство.|We can scale up production later.|Мы сможем увеличить производство позже.|The team needs to scale up its support.|Команде нужно расширить поддержку.
fall short|не дотянуть; оказаться недостаточным|fail to reach a required standard|Fall short of — не достигнуть чего-то.|The result fell short of our target.|Результат не достиг нашей цели.|The service fell short of expectations.|Сервис не оправдал ожиданий.
take a step back|посмотреть шире; отступить на шаг|pause to reconsider the whole situation|Часто о необходимости посмотреть на ситуацию целиком.|Let's take a step back and review the facts.|Давай посмотрим шире и проверим факты.|I need to take a step back from this argument.|Мне нужно отстраниться от этого спора.
go over|проверить; пройтись по|review information carefully|Go over the figures — проверить цифры.|Could we go over the figures again?|Можем ещё раз проверить цифры?|I'll go over the plan with you.|Я разберу план вместе с тобой.
spell out|чётко объяснить|explain in explicit detail|Spell out the consequences — подробно объяснить последствия.|Please spell out what you need.|Пожалуйста, чётко объясни, что тебе нужно.|The contract spells out our obligations.|В договоре подробно описаны наши обязанности.
back up a claim|подтвердить утверждение|support a statement with evidence|Back something up with evidence — подкрепить данными.|Can you back up that claim?|Можешь подтвердить это утверждение?|The figures back up her claim.|Цифры подтверждают её утверждение.
on the same page|одинаково понимать ситуацию|sharing an understanding|Make sure we're on the same page — убедиться в общем понимании.|Let's make sure we're on the same page.|Давай убедимся, что мы одинаково всё понимаем.|We're finally on the same page.|Наконец мы пришли к общему пониманию.
get the ball rolling|дать старт делу|start a process|Разговорное выражение о начале работы.|Let's get the ball rolling today.|Давай начнём дело сегодня.|Her proposal got the ball rolling.|Её предложение дало старт работе.
weigh in|высказать своё мнение|join a discussion with a view|Weigh in on an issue — высказаться по вопросу.|Would you like to weigh in?|Хочешь высказать своё мнение?|Several colleagues weighed in on the issue.|Несколько коллег высказались по этому вопросу.
push back|возразить; сопротивляться|oppose an idea or request|Push back on a proposal — возразить против предложения.|The team pushed back on the deadline.|Команда возразила против этого срока.|It's okay to push back politely.|Можно вежливо возразить.
meet halfway|пойти на взаимный компромисс|each give up part of a demand|Meet someone halfway — пойти навстречу, ожидая взаимности.|Can we meet halfway on the price?|Можем найти компромисс по цене?|Both sides agreed to meet halfway.|Обе стороны согласились пойти на взаимные уступки.
draw the line|обозначить предел|set a limit you will not cross|Draw the line at — считать что-то недопустимым.|I draw the line at working every weekend.|Я не согласен работать каждые выходные.|We need to draw the line somewhere.|Нам нужно где-то установить границу.
hold someone accountable|требовать ответственности|require someone to answer for their actions|Hold someone accountable for — требовать ответа за.|Managers are held accountable for results.|С руководителей спрашивают за результаты.|We should hold ourselves accountable too.|Нам тоже следует отвечать за свои действия.
put things into perspective|помочь оценить масштаб|show the wider context of a situation|Помогает понять, насколько проблема велика на общем фоне.|The comparison puts things into perspective.|Это сравнение помогает оценить масштаб.|A short break helped me put things into perspective.|Короткий перерыв помог мне взглянуть на всё шире.
`,
 C1:`
contentious|спорный; вызывающий разногласия|likely to cause disagreement|A contentious issue — вопрос, вызывающий споры.|This remains a contentious issue.|Этот вопрос по-прежнему вызывает споры.|The most contentious point is the cost.|Самый спорный момент — стоимость.
salient|наиболее заметный; существенный|especially important or noticeable|Salient points — ключевые моменты.|Let me summarise the salient points.|Позволь подытожить ключевые моменты.|Cost is the most salient difference.|Стоимость — самое существенное различие.
inadvertent|непреднамеренный|done without intention|An inadvertent error — непреднамеренная ошибка.|The omission was inadvertent.|Пропуск был непреднамеренным.|We corrected an inadvertent error.|Мы исправили случайную ошибку.
conducive|способствующий|making a good result more likely|Conducive to — благоприятный для.|The setting is conducive to learning.|Эта обстановка способствует учёбе.|Noise isn't conducive to concentration.|Шум не способствует концентрации.
pertinent|относящийся к делу|directly relevant to the matter|Pertinent to — имеющий отношение к.|That's a pertinent question.|Это вопрос по существу.|Please include only pertinent details.|Включи только относящиеся к делу подробности.
susceptible|подверженный; восприимчивый|easily affected by something|Susceptible to — подверженный чему-то.|The system is susceptible to failure.|Эта система подвержена сбоям.|Children may be more susceptible to infections.|Дети могут быть более восприимчивы к инфекциям.
untenable|несостоятельный; неприемлемый|impossible to defend or maintain|An untenable position — позиция, которую невозможно обосновать.|That argument is untenable.|Этот довод несостоятелен.|The situation has become untenable.|Ситуация стала неприемлемой.
equivocal|неоднозначный; уклончивый|allowing different interpretations|An equivocal response — неоднозначный ответ.|The evidence is equivocal.|Данные неоднозначны.|He gave an equivocal response.|Он дал уклончивый ответ.
unequivocal|недвусмысленный|completely clear|Unequivocal support — безоговорочная поддержка.|We need an unequivocal answer.|Нам нужен недвусмысленный ответ.|She expressed unequivocal support.|Она выразила безоговорочную поддержку.
tangible|ощутимый; осязаемый|real and clearly noticeable|Tangible benefits — ощутимые преимущества.|We need tangible results.|Нам нужны ощутимые результаты.|The change brought tangible benefits.|Изменение принесло ощутимую пользу.
intangible|неосязаемый; нематериальный|not physically measurable or touchable|Intangible benefits — нематериальные преимущества.|Trust is an intangible asset.|Доверие — нематериальный актив.|The benefits are largely intangible.|Преимущества в основном нематериальные.
unwarranted|необоснованный|not justified by the facts|Unwarranted criticism — необоснованная критика.|That conclusion is unwarranted.|Этот вывод необоснован.|The criticism seemed unwarranted.|Критика казалась необоснованной.
imperative|крайне необходимый|essential and urgent|It's imperative that — крайне важно, чтобы.|It's imperative that we act quickly.|Крайне важно, чтобы мы действовали быстро.|Clear communication is imperative.|Чёткая коммуникация крайне необходима.
discerning|проницательный; разборчивый|able to judge quality well|A discerning buyer — разборчивый покупатель.|Discerning buyers notice the difference.|Разборчивые покупатели замечают разницу.|She has a discerning eye for quality.|Она умеет хорошо оценивать качество.
meticulous|скрупулёзный|very careful about details|Meticulous attention to detail — тщательное внимание к деталям.|The report requires meticulous checking.|Отчёт требует тщательной проверки.|She's meticulous about keeping records.|Она очень тщательно ведёт записи.
piecemeal|по частям; несистемный|done in separate stages without a whole plan|A piecemeal approach — решение по частям без общей системы.|Piecemeal changes won't solve this.|Несистемные изменения не решат эту проблему.|The information arrived piecemeal.|Информация поступала по частям.
overarching|общий; объединяющий|covering all parts of something|An overarching goal — общая цель.|What is our overarching goal?|Какова наша общая цель?|We need an overarching strategy.|Нам нужна общая стратегия.
contingency plan|резервный план|a plan for unexpected circumstances|Отдельный план действий на случай сбоев.|Do we have a contingency plan?|У нас есть резервный план?|The contingency plan covers power outages.|Резервный план предусматривает отключение электричества.
spillover|побочный эффект на соседние области|effects spreading beyond the original area|Spillover effects — последствия, выходящие за исходные рамки.|The policy had positive spillover effects.|Мера дала положительный эффект и в других областях.|We need to consider the spillover into other teams.|Нужно учесть влияние на другие команды.
leverage|возможность влияния; рычаг|power to influence a situation|Negotiating leverage — преимущество на переговорах.|This gives us more negotiating leverage.|Это усиливает нашу позицию на переговорах.|We have limited leverage over the supplier.|Наше влияние на поставщика ограничено.
take issue with|не согласиться с; оспорить|object to a particular point|Take issue with a claim — оспорить утверждение.|I take issue with that assumption.|Я не согласен с этим предположением.|She took issue with the wording.|Она возразила против формулировки.
by the same token|по той же логике|for the same reason|Связывает похожий аргумент с уже сказанным.|The price matters; by the same token, so does quality.|Цена важна; по той же логике важно и качество.|By the same token, we should review the other contract.|По той же логике нам стоит проверить и другой договор.
in light of|в свете; учитывая|considering new information|In light of the evidence — учитывая имеющиеся данные.|We changed the plan in light of the results.|Мы изменили план с учётом результатов.|In light of this, we should wait.|Учитывая это, нам стоит подождать.
in the absence of|при отсутствии|when something is missing|In the absence of evidence — при отсутствии данных.|In the absence of evidence, we can't conclude anything.|Без доказательств мы не можем делать выводы.|Use email in the absence of a phone number.|Если нет номера телефона, используй почту.
for the sake of argument|допустим, для обсуждения|temporarily assuming something for discussion|Позволяет рассмотреть предположение без согласия с ним.|For the sake of argument, let's assume you're right.|Допустим для обсуждения, что ты прав.|Let's ignore the cost for the sake of argument.|Для обсуждения пока не будем учитывать стоимость.
on balance|взвесив всё; в целом|after considering all advantages and disadvantages|Итог после сравнения плюсов и минусов.|On balance, the benefits outweigh the risks.|Если взвесить всё, польза перевешивает риски.|On balance, I'd accept the offer.|Взвесив всё, я бы принял предложение.
to all intents and purposes|фактически; практически|in every practical sense|О фактическом положении, даже если формально иначе.|The project is, to all intents and purposes, finished.|Проект фактически завершён.|To all intents and purposes, it's the same service.|Практически это тот же сервис.
a moot point|спорный или уже несущественный вопрос|a debatable question or one without practical relevance|В США часто значит «уже не имеет значения»; в Британии также «спорный».|Whether he agreed is now a moot point.|Согласился ли он, теперь уже несущественно.|The exact date remains a moot point.|Точная дата остаётся спорным вопросом.
beg the question|предполагать то, что требуется доказать|use the conclusion as an unproved premise|В строгом смысле — ошибка рассуждения; разговорное «вызывать вопрос» неоднозначно.|That argument begs the question.|Этот довод предполагает то, что требуется доказать.|We should avoid begging the question.|Нам следует избегать кругового обоснования.
draw a distinction|провести различие|separate two concepts carefully|Draw a distinction between — провести различие между.|We must draw a distinction between intent and impact.|Нужно различать намерение и последствия.|She drew a useful distinction.|Она провела полезное различие.
make a compelling case|убедительно обосновать|present strong reasons for something|Make a case for — обосновать необходимость чего-то.|She made a compelling case for the change.|Она убедительно обосновала необходимость изменения.|Can we make a compelling case for this expense?|Можем убедительно обосновать эти затраты?
with that in mind|учитывая это|considering what was just said|Связывает решение с предыдущим соображением.|With that in mind, let's simplify the plan.|Учитывая это, давай упростим план.|Choose a date with that in mind.|Выбирай дату с учётом этого.
at face value|за чистую монету|accepting the apparent meaning without checking|Take something at face value — поверить без проверки.|Don't take the figures at face value.|Не принимай эти цифры за чистую монету.|I took his promise at face value.|Я поверил его обещанию без оговорок.
put paid to|положить конец; сорвать|stop something from happening|Британское выражение: put paid to a plan — сорвать план.|The storm put paid to our picnic.|Буря сорвала наш пикник.|The new evidence put paid to that theory.|Новые данные положили конец этой теории.
leave no stone unturned|сделать всё возможное|try every possible way|О тщательном поиске или попытках решить задачу.|We left no stone unturned in the search.|Мы испробовали всё в поисках.|She'll leave no stone unturned to find the answer.|Она сделает всё возможное, чтобы найти ответ.
sit on the fence|не занимать сторону|avoid taking a position|Нейтральность или нерешительность в споре.|You can't sit on the fence forever.|Нельзя вечно уклоняться от выбора стороны.|He sat on the fence during the debate.|Во время спора он не занял ничью сторону.
move the goalposts|менять правила по ходу дела|change the conditions after someone starts|О несправедливом изменении критериев.|They keep moving the goalposts.|Они постоянно меняют правила по ходу дела.|Let's agree on criteria and not move the goalposts.|Давай согласуем критерии и не будем их менять.
put the cart before the horse|делать в неверном порядке|do things in the wrong sequence|Начать с шага, который должен следовать позже.|Buying equipment now would put the cart before the horse.|Покупать оборудование сейчас — делать всё в неверном порядке.|Let's check demand first, not put the cart before the horse.|Давай сначала проверим спрос, чтобы не делать всё в неверном порядке.
a foregone conclusion|заранее предрешённый исход|a result regarded as certain|Не обязательно означает доказанный факт, лишь ожидаемый итог.|The outcome isn't a foregone conclusion.|Исход ещё не предрешён.|They treated approval as a foregone conclusion.|Они считали одобрение заранее предрешённым.
the crux of the matter|суть вопроса|the central point of an issue|The crux — центральная, самая важная часть.|Cost is the crux of the matter.|Стоимость — суть этого вопроса.|Let's get to the crux of the matter.|Давай перейдём к сути вопроса.
`
};
export const AUTUMN_VOCABULARY=Object.entries(banks).flatMap(([level,bank])=>bank.trim().split('\n').map(line=>{
 const [phrase,ru,explanation,usageRu,en1,ru1,en2,ru2]=line.split('|');
 if(!ru2)throw new Error('Incomplete bilingual card: '+phrase);
 return {id:'lex-'+level.toLowerCase()+'-'+phrase.toLowerCase().replace(/[^a-z0-9]+/g,'-'),level,phrase,ru,explanation,usageRu,
  kind:phrase.includes(' ')?'phrase':'word',pack:'2026-10',examples:[en1,en2],exampleRu:[ru1,ru2],cloze:true};
}));
