// Original, offline notes for words whose grammatical/idiomatic meaning is
// easily lost in an isolated machine translation. Examples are authored here.
const entry=(ru,note,...pairs)=>({ru,note,examples:pairs.map(([en,translation])=>({en,ru:translation}))});
export const WORD_NOTES={
  will:entry('показатель будущего: сделаю, будет…','Will + начальная форма: прогноз, обещание или решение сейчас. Это не «бы». В обычном First Conditional: if + настоящее → will + глагол.',
    ['I will call you after work.','Я позвоню тебе после работы.'],['If it rains, we will stay home.','Если пойдёт дождь, мы останемся дома.']),
  would:entry('бы; также будущее с точки зрения прошлого','Would + глагол часто описывает воображаемый результат. If I lived… — «если бы я жил…», поэтому would walk — «ходил бы пешком». В косвенной речи would может заменять will, а в просьбах добавляет вежливость.',
    ['If I had a bike, I would cycle to work.','Если бы у меня был велосипед, я бы ездил на работу на велосипеде.'],['Would you help me with this bag?','Не мог бы ты помочь мне с этой сумкой?']),
  if:entry('если; в воображаемом условии — если бы','If вводит условие. Смысл определяется обеими частями предложения, а не одним словом if.',
    ['If I finish early, I will cook dinner.','Если я закончу рано, я приготовлю ужин.'],['If I had more space, I would buy a desk.','Если бы у меня было больше места, я бы купил письменный стол.']),
  work:entry('работать; действовать, подходить; работа','Смысл зависит от сочетания. Work at a company — работать в компании; the phone works — телефон работает; works for me — меня устраивает.',
    ['I work near the station.','Я работаю недалеко от станции.'],['Thursday works for me.','Четверг меня устраивает.']),
  live:entry('жить; live как прилагательное — в прямом эфире','Live/lived о месте жительства — «жить/жил». В If I lived… прошедшая форма может обозначать воображаемое настоящее: «если бы я жил…».',
    ['We live near the sea.','Мы живём недалеко от моря.'],['If I lived in London, I would use the bus.','Если бы я жил в Лондоне, я бы ездил на автобусе.']),
  depend:entry('зависеть; полагаться на','Depend on something — зависеть от чего-то. Depend on someone может означать «рассчитывать на кого-то». После he/she/it: depends.',
    ['The price depends on the size.','Цена зависит от размера.'],['You can depend on me.','Ты можешь на меня рассчитывать.']),
  get:entry('получать; становиться; добираться','Get меняет значение в сочетаниях: get ready — подготовиться, get home — добраться домой, get better — становиться лучше.',
    ['I get home at seven.','Я прихожу домой в семь.'],['It is getting colder.','Становится холоднее.']),
  take:entry('брать; занимать время; ехать на транспорте','Take a bus — поехать на автобусе, take a break — сделать перерыв. Не всегда переводится как «брать».',
    ['I take the bus to work.','Я езжу на работу на автобусе.'],['The journey takes twenty minutes.','Дорога занимает двадцать минут.']),
  make:entry('делать; создавать; заставлять','В устойчивых сочетаниях переводим весь смысл: make a mistake — ошибиться, make sense — иметь смысл.',
    ['Everyone makes mistakes.','Все ошибаются.'],['This plan makes sense.','В этом плане есть смысл.']),
  do:entry('делать; вспомогательный глагол','В вопросе Do you work? слово do помогает построить вопрос и отдельно не переводится. Did показывает прошлое; после него основной глагол без окончания.',
    ['What do you do after work?','Что ты делаешь после работы?'],['Did you call her yesterday?','Ты звонил ей вчера?']),
  have:entry('иметь; вспомогательный глагол в Perfect','Have lunch — обедать. Have/has + третья форма строит Present Perfect; had + третья форма — Past Perfect.',
    ['I have two tickets.','У меня два билета.'],['I have already booked the hotel.','Я уже забронировал отель.']),
  be:entry('быть; в настоящем часто не переводится','Am/is/are — настоящее, was/were — прошлое, been — третья форма. Be также помогает строить длительные времена и пассив.',
    ['She is at home.','Она дома.'],['The tickets were sent yesterday.','Билеты отправили вчера.']),
  can:entry('мочь; уметь','Can + глагол без to: способность, возможность или разрешение. Can’t также выражает невозможность: «не может быть».',
    ['I can hear you now.','Теперь я тебя слышу.'],['You can take a break.','Ты можешь сделать перерыв.']),
  could:entry('мог; мог бы; не мог бы…?','Could — способность в прошлом, возможный вариант или вежливая просьба. Перевод зависит от ситуации.',
    ['Could you speak more slowly?','Не мог бы ты говорить помедленнее?'],['We could take a later train.','Мы могли бы поехать более поздним поездом.']),
  should:entry('следует; стоит; должен бы','Обычно это совет или ожидаемый результат, а не строгая обязанность.',
    ['You should check the address.','Тебе стоит проверить адрес.'],['The train should arrive soon.','Поезд должен скоро прибыть.']),
  must:entry('должен; должно быть','Must может выражать обязанность или уверенный вывод. Must be tired — «должно быть, устал».',
    ['You must wear a seat belt.','Ты должен пристегнуть ремень.'],['She must be tired after the trip.','Она, должно быть, устала после поездки.']),
  might:entry('возможно; может быть','Might + начальная форма выражает неуверенную возможность.',
    ['It might rain this evening.','Возможно, вечером пойдёт дождь.'],['We might leave a little later.','Возможно, мы уедем немного позже.']),
  may:entry('может; возможно; разрешено','May обозначает возможность или формальное разрешение. Название месяца May — май.',
    ['The meeting may start late.','Возможно, встреча начнётся с опозданием.'],['May I ask a question?','Можно задать вопрос?']),
  to:entry('к; в; частица перед глаголом','To work после want означает «работать», а go to work — «идти на работу». У служебных слов нет одного перевода для всех ситуаций.',
    ['I want to learn.','Я хочу учиться.'],['We walked to the station.','Мы дошли до станции пешком.']),
  for:entry('для; за; в течение','For a friend — для друга, for two hours — в течение двух часов, pay for — платить за.',
    ['This gift is for you.','Этот подарок для тебя.'],['I waited for ten minutes.','Я ждал десять минут.']),
  on:entry('на; по; в определённый день','On Monday — в понедельник. Depend on — зависеть от; здесь предлог переводится вместе с глаголом.',
    ['The keys are on the table.','Ключи на столе.'],['We will meet on Monday.','Мы встретимся в понедельник.']),
  in:entry('в; через; за определённый срок','In the room — в комнате; in ten minutes — через десять минут.',
    ['She is in the kitchen.','Она на кухне.'],['I will be ready in five minutes.','Я буду готов через пять минут.']),
  at:entry('в; у; на — точка места или времени','At six — в шесть; at work — на работе; at the door — у двери.',
    ['We start at nine.','Мы начинаем в девять.'],['I am at the bus stop.','Я на автобусной остановке.']),
  of:entry('из; о; часто передаёт родительный падеж','A cup of tea — чашка чая. Переводим сочетание, а не механически добавляем «из».',
    ['I would like a cup of tea.','Я бы хотел чашку чая.'],['This is the end of the street.','Это конец улицы.']),
  a:entry('неопределённый артикль; обычно без отдельного перевода','A/an ставят перед одним исчисляемым предметом, который ещё не выделен как конкретный. An — перед гласным звуком.',
    ['I need a ticket.','Мне нужен билет.'],['She bought a new bag.','Она купила новую сумку.']),
  an:entry('неопределённый артикль перед гласным звуком','Выбор a/an зависит от звука: an hour, но a university. Обычно артикль отдельно не переводится.',
    ['We waited for an hour.','Мы ждали час.'],['I have an idea.','У меня есть идея.']),
  the:entry('определённый артикль; обычно без отдельного перевода','The показывает: собеседнику понятно, о каком именно предмете речь.',
    ['Please close the door.','Пожалуйста, закрой дверь.'],['I saw a dog. The dog was friendly.','Я увидел собаку. Эта собака была дружелюбной.']),
  that:entry('тот; это; что; который','That может указывать на предмет или связывать части предложения. That works for me — «меня это устраивает».',
    ['That sounds good.','Звучит хорошо.'],['I know that she is busy.','Я знаю, что она занята.']),
  by:entry('к; у; с помощью; кем-то','By Friday — к пятнице; by bus — на автобусе. В пассиве by указывает исполнителя.',
    ['Please finish it by Friday.','Пожалуйста, закончи это к пятнице.'],['We travel by bus.','Мы ездим на автобусе.']),
  as:entry('как; в качестве; поскольку','As a teacher — в качестве учителя. As…as используется для сравнения.',
    ['She works as a teacher.','Она работает учителем.'],['This bag is as heavy as mine.','Эта сумка такая же тяжёлая, как моя.']),
  still:entry('всё ещё; по-прежнему','Still подчёркивает, что ситуация продолжается. В других контекстах означает «неподвижный» или «тем не менее».',
    ['I am still waiting for the bus.','Я всё ещё жду автобус.'],['She still works here.','Она по-прежнему работает здесь.']),
  yet:entry('ещё; уже — в вопросе','Not yet — ещё нет. Have you finished yet? — Ты уже закончил? Yet также может связывать контрастные мысли: «и всё же».',
    ['I have not finished yet.','Я ещё не закончил.'],['Have you booked the tickets yet?','Ты уже забронировал билеты?']),
  since:entry('с; с тех пор как; поскольку','Since Monday задаёт начало периода. В другом контексте since может указывать причину.',
    ['I have lived here since May.','Я живу здесь с мая.'],['Since it is late, let us go home.','Поскольку уже поздно, давай пойдём домой.']),
  than:entry('чем — при сравнении','После сравнительной формы than вводит второй объект.',
    ['This route is shorter than the other one.','Этот маршрут короче другого.'],['Today is warmer than yesterday.','Сегодня теплее, чем вчера.']),
  there:entry('там; в there is/are — есть, находится','There is a café — «здесь есть кафе». В этой конструкции there не обязательно означает «там».',
    ['There is a café nearby.','Рядом есть кафе.'],['I left my bag there.','Я оставил сумку там.']),
  it:entry('это; он/она/оно о предмете; иногда без перевода','It заменяет предмет или ситуацию. В It is raining слово it служебное и отдельно не переводится.',
    ['It is raining.','Идёт дождь.'],['I bought a book. It is interesting.','Я купил книгу. Она интересная.'])
};

// Small, transparent aliases, not an unrestricted stemmer: news != new,
// business != bus, and an apostrophe is not silently dropped.
export const WORD_FORMS={
  works:'work',worked:'work',working:'work',lived:'live',lives:'live',living:'live',depends:'depend',depended:'depend',depending:'depend',
  gets:'get',got:'get',gotten:'get',getting:'get',takes:'take',took:'take',taken:'take',taking:'take',makes:'make',made:'make',making:'make',
  does:'do',did:'do',done:'do',doing:'do',has:'have',had:'have',having:'have',am:'be',is:'be',are:'be',was:'be',were:'be',been:'be',being:'be',
  walked:'walk',walking:'walk',walks:'walk',improves:'improve',improved:'improve',improving:'improve',required:'require',requires:'require',
  considered:'consider',considers:'consider',avoids:'avoid',avoided:'avoid',suggested:'suggest',suggests:'suggest',achieved:'achieve',achieves:'achieve'
};

export const CONTRACTIONS={
  "i'm":['I am','я…; я являюсь/нахожусь…'],"you're":['you are','ты…; вы…'],"we're":['we are','мы…'],"they're":['they are','они…'],
  "it's":['it is / it has','это…; либо it has перед третьей формой'],"that's":['that is / that has','это…; либо that has перед третьей формой'],
  "he's":['he is / he has','он…; либо he has перед третьей формой'],"she's":['she is / she has','она…; либо she has перед третьей формой'],
  "i've":['I have','у меня есть; либо часть Present Perfect'],"you've":['you have','у тебя есть; либо часть Present Perfect'],"we've":['we have','у нас есть; либо часть Present Perfect'],"they've":['they have','у них есть; либо часть Present Perfect'],
  "i'll":['I will','я сделаю/буду…'],"you'll":['you will','ты сделаешь/будешь…'],"we'll":['we will','мы сделаем/будем…'],"they'll":['they will','они сделают/будут…'],"he'll":['he will','он сделает/будет…'],"she'll":['she will','она сделает/будет…'],
  "i'd":['I would / I had','я бы…; либо I had перед третьей формой'],"you'd":['you would / you had','ты бы…; либо you had перед третьей формой'],"we'd":['we would / we had','мы бы…; либо we had перед третьей формой'],
  "can't":['cannot','не могу; не может быть'],cannot:['cannot','не могу; не может быть'],"couldn't":['could not','не мог; не мог бы'],"won't":['will not','не сделаю/не будет…'],"wouldn't":['would not','не сделал бы…'],
  "don't":['do not','не… — отрицание в настоящем'],"doesn't":['does not','не… — с he/she/it в настоящем'],"didn't":['did not','не… — отрицание в прошлом'],
  "isn't":['is not','не является/не находится…'],"aren't":['are not','не являемся/не находимся…'],"wasn't":['was not','не был/не была…'],"weren't":['were not','не были…'],
  "haven't":['have not','ещё не… — в Present Perfect'],"hasn't":['has not','ещё не… — с he/she/it в Present Perfect'],"hadn't":['had not','не… — в Past Perfect'],"let's":['let us','давай; давайте']
};

export const CONTEXT_PHRASES=[
  {pattern:/\bworks? for (me|you|us|them|him|her)\b/gi,ru:'устраивает, подходит — о времени или плане; работает на кого-то — о работе',note:'That works for me — «меня это устраивает». Но She works for me — «она работает у меня». Смотри, что или кто стоит перед works.',examples:[...WORD_NOTES.work.examples.slice(1),{en:'She works for me at the café.',ru:'Она работает у меня в кафе.'}]},
  {pattern:/\b(?:depend|depends|depended|depending) on\b/gi,ru:'зависеть от; рассчитывать на',note:'С обстоятельством — «зависеть от». С человеком также бывает «полагаться на».',examples:WORD_NOTES.depend.examples},
  {pattern:/\b(?:make|makes|made) sense\b/gi,ru:'иметь смысл; быть понятным',examples:WORD_NOTES.make.examples.slice(1)},
  {pattern:/\b(?:take|takes|took|taking) (?:a |the )?bus\b/gi,ru:'ехать на автобусе',examples:WORD_NOTES.take.examples.slice(0,1)},
  {pattern:/\b(?:look|looks|looking) forward to\b/gi,ru:'с нетерпением ждать',note:'После to здесь существительное или -ing: look forward to seeing you.',examples:[{en:'I look forward to seeing you.',ru:'С нетерпением жду встречи с тобой.'}]},
  {pattern:/\b(?:run|runs|running|ran) out of\b/gi,ru:'заканчиваться; исчерпать запас',examples:[{en:'We are running out of time.',ru:'У нас заканчивается время.'}]},
  {pattern:/\b(?:pick|picks|picked|picking) (?:me|you|us|them|him|her) up\b/gi,ru:'заехать за кем-то; забрать',examples:[{en:'I will pick you up at six.',ru:'Я заеду за тобой в шесть.'}]}
];
